mod award_document_to_winner;
mod check_for_ended_vote_polls;
mod clean_up_after_contested_resources_vote_polls_end;
mod clean_up_after_vote_polls_end;
mod keep_record_of_vote_poll;
mod remove_votes_for_removed_masternodes;
mod run_dao_platform_events;
mod tally_votes_for_contested_document_resource_vote_poll;
