"""Deterministic ownership, review evidence and admission decisions."""

import copy
import hashlib
import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path

STATE_MARKER = 'platform-pr-review-state-v1'
BOTS = {'thepastaclaw', 'coderabbitai', 'coderabbitai[bot]'}
WRITE = {'write', 'maintain', 'admin'}


def _time(value):
    parsed = datetime.fromisoformat(value.replace('Z', '+00:00'))
    if parsed.tzinfo is None:
        raise ValueError('Timestamp requires timezone')
    return parsed


def _fields(value, allowed, required):
    if not isinstance(value, dict) or set(value) - allowed or required - set(value):
        raise ValueError('Unknown or missing policy fields')


def _handles(values, nonempty=False):
    if not isinstance(values, list) or (nonempty and not values):
        raise ValueError('Expected handle list')
    seen = set()
    for handle in values:
        if not isinstance(handle, str) or not re.fullmatch(r'[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?', handle):
            raise ValueError('Malformed GitHub handle')
        if handle.lower() in seen or handle.lower() in {'strophy', 'silvanassss'}:
            raise ValueError('Duplicate or excluded identity')
        seen.add(handle.lower())


def validate_policy(policy, root: Path | None = None):
    keys = {'version', 'repository', 'fallback', 'max_active_prs', 'target_branches', 'areas'}
    _fields(policy, keys, keys)
    if type(policy['version']) is not int or policy['version'] != 1:
        raise ValueError('Unsupported policy version')
    if not isinstance(policy['repository'], str) or not re.fullmatch(r'[\w.-]+/[\w.-]+', policy['repository']):
        raise ValueError('Invalid repository')
    if type(policy['max_active_prs']) is not int or policy['max_active_prs'] != 5:
        raise ValueError('Expected five active slots')
    branches = policy['target_branches']
    if not isinstance(branches, list) or not branches or any(not isinstance(x, str) or not x.strip() for x in branches) or len(set(branches)) != len(branches):
        raise ValueError('Invalid target branches')
    _fields(policy['fallback'], {'owners', 'reviewers'}, {'owners', 'reviewers'})
    _handles(policy['fallback']['owners'], True)
    _handles(policy['fallback']['reviewers'])
    if not isinstance(policy['areas'], list):
        raise ValueError('Expected areas list')
    names, prefixes = set(), []
    for area in policy['areas']:
        _fields(area, {'id', 'paths', 'owners', 'reviewers', 'unresolved', 'metadata'}, {'id', 'paths', 'owners', 'reviewers'})
        if not isinstance(area['id'], str) or not re.fullmatch(r'[a-z0-9][a-z0-9-]*', area['id']) or area['id'] in names or area['id'] == 'fallback':
            raise ValueError('Invalid or duplicate area id')
        names.add(area['id'])
        _handles(area['owners'], True)
        _handles(area['reviewers'])
        if {x.lower() for x in area['owners']} & {x.lower() for x in area['reviewers']}:
            raise ValueError('Owner and reviewer roles overlap')
        if 'unresolved' in area and (not isinstance(area['unresolved'], list) or any(not isinstance(x, str) or not x.strip() for x in area['unresolved'])):
            raise ValueError('Invalid unresolved identities')
        if 'metadata' in area and not isinstance(area['metadata'], dict):
            raise ValueError('Invalid area metadata')
        if not isinstance(area['paths'], list) or not area['paths']:
            raise ValueError('Expected literal directory prefixes')
        for prefix in area['paths']:
            if not isinstance(prefix, str) or not re.fullmatch(r'(?:[A-Za-z0-9_.-]+/)+', prefix) or any(x in {'.', '..'} for x in prefix.split('/')):
                raise ValueError('Invalid literal directory prefix')
            if any(prefix.startswith(other) or other.startswith(prefix) for other in prefixes):
                raise ValueError('Overlapping directory prefixes')
            if root is not None and not (root / prefix).is_dir():
                raise ValueError(f'Missing policy directory: {prefix}')
            prefixes.append(prefix)


def codeowners(policy):
    validate_policy(policy)
    lines = ['# Generated by scripts/pr_review/main.py codeowners; edit pr-review-policy.json.',
             '# Owners and reviewers are combined here for native review routing.',
             '* ' + ' '.join('@' + x for x in policy['fallback']['owners'] + policy['fallback']['reviewers'])]
    for area in policy['areas']:
        if area.get('unresolved'):
            lines.append('# Unresolved reviewer identities; see responsibility documentation.')
        people = ' '.join('@' + x for x in area['owners'] + area['reviewers'])
        lines.extend('/' + path + ' ' + people for path in area['paths'])
    return '\n'.join(lines) + '\n'


def effective_admission(pr):
    recorded = (pr.get('controller_state') or {}).get('admitted_at')
    inactive = pr.get('lifecycle_at')
    if recorded and inactive and _time(recorded) <= _time(inactive):
        return None
    return recorded


def admit(policy, prs, nowISO):
    validate_policy(policy)
    _time(nowISO)
    grouped = defaultdict(list)
    for pr in prs:
        if pr['state'] == 'open' and not pr['draft'] and pr['base'] in policy['target_branches']:
            grouped[pr['author'].lower()].append(pr)
    result = {}
    for candidates in grouped.values():
        def order(pr):
            admitted = effective_admission(pr)
            return (0, _time(admitted), pr['number']) if admitted else (1, _time(pr['created_at']), pr['number'])
        for pr in sorted(candidates, key=order)[:policy['max_active_prs']]:
            result[pr['number']] = effective_admission(pr) or nowISO
    return result


def fingerprint(pr):
    relevant = copy.deepcopy(pr)
    for name in ('controller_state', 'controller_comment_id', 'labels', 'requested_reviewers'):
        relevant.pop(name, None)
    relevant['comments'] = [x for x in relevant.get('comments', []) if not (
        x.get('user', '').lower() == 'github-actions[bot]' and
        x.get('body', '').startswith(f'<!-- {STATE_MARKER}'))]
    for name in ('comments', 'reviews', 'threads', 'files'):
        if name in relevant:
            relevant[name] = sorted(relevant[name], key=lambda x: json.dumps(x, sort_keys=True))
    return hashlib.sha256(json.dumps(relevant, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def _latest_reviews(reviews):
    latest = {}
    for review in sorted(reviews, key=lambda x: (_time(x['submitted_at']), x['id'])):
        state = review['state'].upper()
        if state in {'APPROVED', 'CHANGES_REQUESTED', 'DISMISSED'}:
            latest[review['user'].lower()] = review
    return latest


def _rabbit_receipt(body, head):
    # The producer embeds a JSON object directly after its named HTML marker.
    for marker in re.finditer(r'(?m)^<!-- final_review_risk_coverage:\s*', body):
        try:
            value, end = json.JSONDecoder().raw_decode(body[marker.end():])
        except (ValueError, TypeError):
            continue
        if not re.match(r'\s*-->[ \t]*(?:\r?\n|$)', body[marker.end() + end:]):
            continue
        if isinstance(value, dict) and value.get('kind') == 'reviewed' and value.get('coveredCommitId') == head:
            return True
    return False


def evaluate(policy, pr, admitted_at, nowISO):
    result = {k: pr.get(k) for k in ('number', 'head', 'author', 'title', 'url')}
    result.update(state='configuration-error', status='error', blockers=[], reviewers=[], areas=[],
                  ready_since=None, admitted_at=admitted_at, bot_completed_at=None, self_reviewed_at=None)

    def stop(state, *reasons, status='pending'):
        result.update(state=state, status=status, blockers=list(reasons))
        return result

    try:
        validate_policy(policy)
        _time(nowISO)
        required = {'number','author','head','base','base_sha','created_at','draft','state','files','reviews','comments','threads','permissions','complete'}
        if required - set(pr) or not pr['complete']:
            return stop('configuration-error', 'Incomplete GitHub snapshot', status='error')
        if not re.fullmatch(r'[0-9a-f]{40}', pr['head']):
            return stop('configuration-error', 'Invalid head SHA', status='error')
        if pr['state'] != 'open' or pr['base'] not in policy['target_branches']:
            return stop('configuration-error', 'PR is outside the active policy scope')
        if pr['draft']:
            return stop('draft', 'Draft PR does not occupy a review slot')
        if not admitted_at:
            return stop('waiting-slot', 'Waiting for one of five author review slots')
        _time(admitted_at)
        if not pr['files']:
            return stop('configuration-error', 'No changed-file evidence', status='error')
        touched = {}
        for file in pr['files']:
            for path in {file['filename'], file.get('previous_filename', file['filename'])}:
                if not isinstance(path, str) or path.startswith('/') or any(x in {'.','..',''} for x in path.split('/')):
                    raise ValueError('Invalid changed path')
                area = next((a for a in policy['areas'] if any(path.startswith(p) for p in a['paths'])), None)
                area = area or dict(policy['fallback'], id='fallback')
                touched[area['id']] = area
        result['areas'] = sorted(touched)
        permissions = {k.lower(): v for k,v in pr['permissions'].items()}
        people = {x.lower(): x for a in touched.values() for x in a['owners'] + a['reviewers']}
        for area in touched.values():
            if area.get('unresolved'):
                return stop('configuration-error', 'Unresolved identities in ' + area['id'], status='error')
        if any(permissions.get(x) not in WRITE for x in people):
            return stop('configuration-error', 'An assigned owner/reviewer lacks verified write access', status='error')
        latest = _latest_reviews(pr['reviews'])
        bot_blocks = [r for u,r in latest.items() if u in BOTS and r['state'].upper() == 'CHANGES_REQUESTED']
        bot_threads = [t for t in pr['threads'] if not t['is_resolved'] and t['author'].lower() in BOTS]
        pasta, rabbit = [], []
        for review in pr['reviews']:
            user, state = review['user'].lower(), review['state'].upper()
            if review['commit_id'] != pr['head']:
                continue
            if user == 'thepastaclaw' and state in {'APPROVED','COMMENTED'} and re.search(
                r'(?m)^<!-- thepastaclaw-review-phase v1 phase=final sha=' + re.escape(pr['head']) + r'(?:\s+[^<>]*?)?\s*-->', review['body']):
                pasta.append(review['submitted_at'])
            if user in {'coderabbitai','coderabbitai[bot]'} and state == 'APPROVED':
                rabbit.append(review['submitted_at'])
        for comment in pr['comments']:
            if comment['user'].lower() in {'coderabbitai','coderabbitai[bot]'} and _rabbit_receipt(comment['body'], pr['head']):
                rabbit.append(comment['updated_at'])
        if not pasta or not rabbit or bot_blocks or bot_threads:
            reasons = []
            if not pasta: reasons.append('thepastaclaw final review missing for current head')
            if not rabbit: reasons.append('CodeRabbit completion missing for current head')
            if bot_blocks: reasons.append('Bot changes request remains outstanding')
            if bot_threads: reasons.append('Bot review threads remain unresolved')
            return stop('waiting-bots', *reasons)
        completed = max(pasta + rabbit, key=_time)
        result['bot_completed_at'] = completed
        attestations = [c['created_at'] for c in pr['comments'] if c['user'].lower() == pr['author'].lower()
                        and c['body'] == '/self-reviewed ' + pr['head']
                        and c['created_at'] == c['updated_at'] and _time(c['created_at']) >= _time(completed)]
        if not attestations:
            return stop('waiting-self-review', 'Author must post /self-reviewed ' + pr['head'] + ' after bot completion')
        self_time = max(attestations,key=_time)
        result['self_reviewed_at'] = self_time
        objectors = {}
        for user, review in latest.items():
            if user not in BOTS and permissions.get(user) in WRITE and review['state'].upper() == 'CHANGES_REQUESTED':
                objectors[user] = review['submitted_at']
        for thread in pr['threads']:
            if not thread['is_resolved'] and thread['author'].lower() not in BOTS:
                user = thread['author'].lower()
                objectors[user] = max(objectors.get(user, thread['created_at']), thread['created_at'],key=_time)
        if any(_time(value) >= _time(self_time) for value in objectors.values()):
            return stop('waiting-author', 'Author response is required after the latest human objection')
        author = pr['author'].lower()
        needed = set()
        for area in touched.values():
            if author in {x.lower() for x in area['owners']}:
                continue
            eligible = {x.lower() for x in area['owners'] + area['reviewers']} - {author}
            if not any(u in latest and latest[u]['state'].upper() == 'APPROVED' and latest[u]['commit_id'] == pr['head'] for u in eligible):
                needed.update(eligible)
        needed.update(u for u in objectors if u != author and permissions.get(u) in WRITE and u not in BOTS)
        if needed or objectors:
            result['reviewers'] = sorted(people.get(u,u) for u in needed)
            previous = pr.get('controller_state') or {}
            if previous.get('state') == 'ready-for-human' and previous.get('head') == pr['head'] and previous.get('ready_since'):
                _time(previous['ready_since'])
                result['ready_since'] = previous['ready_since']
            elif previous.get('admitted_at'):
                result['ready_since'] = nowISO
            return stop('ready-for-human', 'Human approval or objection resolution is required')
        return stop('ready-to-merge', status='success')
    except (ValueError, TypeError, KeyError) as error:
        return stop('configuration-error', str(error), status='error')
