mod fetch_contested_document_vote_poll_stored_info;
mod fetch_identities_voting_for_contenders;
mod fetch_identities_voting_in_yes_no_vote_poll;
mod fetch_identity_contested_resource_vote;
mod fetch_identity_yes_no_vote;
mod fetch_yes_no_vote_poll_stored_info;
