pub mod masternode_not_found_error;
pub mod masternode_vote_already_present_error;
pub mod masternode_voted_too_many_times;
pub mod vote_poll_not_available_for_voting_error;
pub mod vote_poll_not_found_error;
