pub mod data_contract_already_present_error;
pub mod data_contract_config_update_error;
pub mod data_contract_is_readonly_error;
pub mod data_contract_not_found_error;
pub mod data_contract_update_action_not_allowed_error;
pub mod data_contract_update_permission_error;
pub mod document_type_update_error;
