use crate::version::drive_versions::drive_verify_method_versions::{
    DriveVerifyAddressFundsMethodVersions, DriveVerifyContractMethodVersions,
    DriveVerifyDocumentCountMethodVersions, DriveVerifyDocumentMethodVersions,
    DriveVerifyDocumentRankedMethodVersions, DriveVerifyDocumentSumMethodVersions,
    DriveVerifyGroupMethodVersions, DriveVerifyIdentityMethodVersions, DriveVerifyMethodVersions,
    DriveVerifyShieldedMethodVersions, DriveVerifySingleDocumentMethodVersions,
    DriveVerifyStateTransitionMethodVersions, DriveVerifySystemMethodVersions,
    DriveVerifyTokenMethodVersions, DriveVerifyVoteMethodVersions,
};

pub const DRIVE_VERIFY_METHOD_VERSIONS_V1: DriveVerifyMethodVersions = DriveVerifyMethodVersions {
    contract: DriveVerifyContractMethodVersions {
        verify_contract: 0,
        verify_contract_history: 0,
        verify_contract_return_serialization: 0,
    },
    document: DriveVerifyDocumentMethodVersions {
        verify_proof: 0,
        verify_proof_keep_serialized: 0,
        verify_document_history: 0,
        verify_start_at_document_in_proof: 0,
    },
    document_count: DriveVerifyDocumentCountMethodVersions {
        verify_aggregate_count_proof: 0,
        verify_carrier_aggregate_count_proof: 0,
        verify_distinct_count_proof: 0,
        verify_point_lookup_count_proof: 0,
        verify_primary_key_count_tree_proof: 0,
    },
    document_sum: DriveVerifyDocumentSumMethodVersions {
        verify_aggregate_sum_proof: 0,
        verify_carrier_aggregate_sum_proof: 0,
        verify_carrier_aggregate_count_and_sum_proof: 0,
        verify_aggregate_count_and_sum_proof: 0,
        verify_primary_key_sum_tree_proof: 0,
        verify_primary_key_count_sum_tree_proof: 0,
        verify_point_lookup_sum_proof: 0,
        verify_distinct_sum_proof: 0,
        verify_distinct_count_and_sum_proof: 0,
        verify_point_lookup_count_and_sum_proof: 0,
    },
    document_ranked: DriveVerifyDocumentRankedMethodVersions {
        verify_ranked_top_k_proof: 0,
        verify_having_range_proof: 0,
    },
    identity: DriveVerifyIdentityMethodVersions {
        verify_full_identities_by_public_key_hashes: 0,
        verify_full_identity_by_identity_id: 0,
        verify_full_identity_by_public_key_hash: 0,
        verify_identity_balance_for_identity_id: 0,
        verify_identity_balances_for_identity_ids: 0,
        verify_identity_balance_revision_and_addresses_from_inputs: 0,
        verify_identity_id_by_unique_public_key_hash: 0,
        verify_identity_ids_by_unique_public_key_hashes: 0,
        verify_identity_keys_by_identity_id: 0,
        verify_identity_nonce: 0,
        verify_identity_contract_nonce: 0,
        verify_identities_contract_keys: 0,
        verify_identity_revision_for_identity_id: 0,
        verify_full_identity_by_non_unique_public_key_hash: 0,
        verify_identity_id_by_non_unique_public_key_hash: 0,
    },
    group: DriveVerifyGroupMethodVersions {
        verify_group_info: 0,
        verify_group_infos_in_contract: 0,
        verify_action_infos: 0,
        verify_action_signers: 0,
        verify_action_signers_total_power: 0,
    },
    token: DriveVerifyTokenMethodVersions {
        verify_token_balances_for_identity_ids: 0,
        verify_token_balances_for_identity_id: 0,
        verify_token_infos_for_identity_ids: 0,
        verify_token_infos_for_identity_id: 0,
        verify_token_statuses: 0,
        verify_token_total_supply_and_aggregated_identity_balance: 0,
        verify_token_balance_for_identity_id: 0,
        verify_token_info_for_identity_id: 0,
        verify_token_status: 0,
        verify_token_pre_programmed_distributions: 0,
        verify_token_direct_selling_price: 0,
        verify_token_direct_selling_prices: 0,
        verify_token_perpetual_distribution_last_paid_time: 0,
        verify_token_contract_info: 0,
    },
    single_document: DriveVerifySingleDocumentMethodVersions {
        verify_proof: 0,
        verify_proof_keep_serialized: 0,
    },
    system: DriveVerifySystemMethodVersions {
        verify_epoch_infos: 0,
        verify_epoch_proposers: 0,
        verify_elements: 0,
        verify_total_credits_in_system: 0,
        verify_upgrade_state: 0,
        verify_upgrade_vote_status: 0,
        verify_finalized_epoch_infos: 0,
    },
    voting: DriveVerifyVoteMethodVersions {
        verify_masternode_vote: 0,
        verify_vote_poll_votes_proof: 0,
        verify_identity_votes_given_proof: 0,
        verify_vote_poll_vote_state_proof: 0,
        verify_contests_proof: 0,
        verify_vote_polls_by_end_date_proof: 0,
        verify_specialized_balance: 0,
    },
    address_funds: DriveVerifyAddressFundsMethodVersions {
        verify_address_info: 0,
        verify_addresses_infos: 0,
        verify_address_funds_trunk_query: 0,
        verify_address_funds_branch_query: 0,
        verify_recent_address_balance_changes: 0,
        verify_compacted_address_balance_changes: 0,
    },
    state_transition: DriveVerifyStateTransitionMethodVersions {
        verify_state_transition_was_executed_with_proof: 0,
    },
    shielded: DriveVerifyShieldedMethodVersions {
        verify_shielded_pool_state: 0,
        verify_shielded_anchors: 0,
        verify_most_recent_shielded_anchor: 0,
        verify_shielded_encrypted_notes: 0,
        verify_shielded_notes_count: 0,
        verify_shielded_nullifiers: 0,
    },
};
