use crate::version::drive_versions::drive_contract_method_versions::{
    DriveContractApplyMethodVersions, DriveContractCostsMethodVersions,
    DriveContractFeePotMethodVersions, DriveContractGetMethodVersions,
    DriveContractInsertMethodVersions, DriveContractMethodVersions,
    DriveContractModerationMethodVersions, DriveContractProveMethodVersions,
    DriveContractUpdateMethodVersions,
};

pub const DRIVE_CONTRACT_METHOD_VERSIONS_V1: DriveContractMethodVersions =
    DriveContractMethodVersions {
        prove: DriveContractProveMethodVersions {
            prove_contract: 0,
            prove_contract_history: 0,
            prove_contracts: 0,
            prove_contracts_by_range: 0,
            prove_contracts_versions: 0,
        },
        apply: DriveContractApplyMethodVersions {
            apply_contract: 0,
            apply_contract_with_serialization: 0,
        },
        insert: DriveContractInsertMethodVersions {
            add_contract_to_storage: 0,
            insert_contract: 0,
            add_description: 0,
            add_keywords: 0,
        },
        update: DriveContractUpdateMethodVersions {
            update_contract: 0,
            update_description: 0,
            update_keywords: 0,
        },
        costs: DriveContractCostsMethodVersions {
            add_estimation_costs_for_contract_insertion: 0,
        },
        get: DriveContractGetMethodVersions {
            fetch_contract: 0,
            fetch_contract_ids: 0,
            fetch_contract_version: 0,
            fetch_contracts: 0,
            fetch_contract_with_history: 0,
            get_cached_contract_with_fetch_info: 0,
            get_contract_with_fetch_info: 0,
            get_contracts_with_fetch_info: 0,
            get_system_or_user_contract_with_fee: 0,
        },
        moderation: DriveContractModerationMethodVersions {
            add_contract_ban: 0,
            remove_contract_ban: 0,
            add_contract_suspension: 0,
            remove_contract_suspension: 0,
            add_contract_warning: 0,
            remove_contract_warnings: 0,
            fetch_contract_moderation_status: 0,
            fetch_contract_moderation_entries: 0,
            prove_contract_moderation_status: 0,
            prove_contract_moderation_entries: 0,
            insert_contract_moderation_trees: 0,
            add_estimation_costs_for_contract_moderation_trees: 0,
            add_estimation_costs_for_contract_moderation_entry: 0,
            add_contract_document_removal: 0,
            fetch_contract_document_removals: 0,
            prove_contract_document_removals: 0,
            insert_contract_document_removal_trees: 0,
            add_estimation_costs_for_contract_document_removal: 0,
            set_contract_moderation_action_count: 0,
            fetch_contract_moderation_action_counts: 0,
            remove_contract_moderation_action_counts: 0,
            add_estimation_costs_for_contract_moderation_action_counts: 0,
        },
        fee_pots: DriveContractFeePotMethodVersions {
            insert_contract_fee_pot_trees: 0,
            add_to_contract_fee_pot: 0,
            deduct_from_contract_fee_pot: 0,
            fetch_contract_fee_pot: 0,
            fetch_action_fee_multiplier: 0,
            set_contract_last_fee_claim: 0,
            prove_contract_fee_pots: 0,
            add_estimation_costs_for_contract_fee_pot_update: 0,
        },
    };
