//! Contract state transition implementations for the WASM SDK.
//!
//! This module provides WASM bindings for contract operations like create and update.

use crate::error::WasmSdkError;
use crate::sdk::WasmSdk;
use crate::settings::{get_user_fee_increase, PutSettingsInput};
use dash_sdk::dpp::data_contract::accessors::v0::DataContractV0Getters;
use dash_sdk::dpp::data_contract::config::moderation::ContractModerationListStatus;
use dash_sdk::dpp::data_contract::DataContract;
use dash_sdk::dpp::identity::identity_public_key::accessors::v0::IdentityPublicKeyGettersV0;
use dash_sdk::dpp::identity::IdentityPublicKey;
use dash_sdk::dpp::platform_value::Identifier;
use dash_sdk::dpp::state_transition::data_contract_update_transition::methods::DataContractUpdateTransitionMethodsV0;
use dash_sdk::dpp::state_transition::data_contract_update_transition::DataContractUpdateTransition;
use dash_sdk::platform::transition::broadcast::BroadcastStateTransition;
use dash_sdk::platform::transition::put_contract::PutContract;
use std::collections::BTreeMap;
use wasm_bindgen::prelude::*;
use wasm_dpp2::data_contract::DataContractWasm;
use wasm_dpp2::identity::IdentityPublicKeyWasm;
use wasm_dpp2::utils::try_from_options_optional;
use wasm_dpp2::IdentitySignerWasm;

// ============================================================================
// Contract Publish
// ============================================================================

/// TypeScript interface for contract publish options
#[wasm_bindgen(typescript_custom_section)]
const CONTRACT_PUBLISH_OPTIONS_TS: &'static str = r#"
/**
 * Options for publishing a new data contract on Dash Platform.
 */
export interface ContractPublishOptions {
  /**
   * The data contract to create.
   * Use `new DataContract(...)` or `DataContract.fromJSON(...)` to construct it.
   */
  dataContract: DataContract;

  /**
   * The identity public key to use for signing the transition.
   * Get this from the owner identity's public keys.
   */
  identityKey: IdentityPublicKey;

  /**
   * Signer containing the private key that corresponds to the identity key.
   * Use IdentitySigner to add the private key before calling.
   */
  signer: IdentitySigner;

  /**
   * Optional settings for the broadcast operation.
   * Includes retries, timeouts, userFeeIncrease, etc.
   */
  settings?: PutSettings;
}
"#;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(typescript_type = "ContractPublishOptions")]
    pub type ContractPublishOptionsJs;
}

#[wasm_bindgen]
impl WasmSdk {
    /// Publish a new data contract on Dash Platform.
    ///
    /// This method handles the complete contract publishing flow:
    /// 1. Validates the contract
    /// 2. Creates and signs the contract create transition
    /// 3. Broadcasts and waits for confirmation
    ///
    /// Note: The contract ID is generated by the platform using the identity nonce
    /// at the time of publishing. The returned contract contains the actual ID.
    ///
    /// @param options - Options including the data contract, public key, and signer
    /// @returns Promise that resolves to the published DataContract with the actual ID
    #[wasm_bindgen(js_name = "contractPublish")]
    pub async fn contract_publish(
        &self,
        options: ContractPublishOptionsJs,
    ) -> Result<DataContractWasm, WasmSdkError> {
        // Extract data contract from options
        let data_contract_wasm = DataContractWasm::try_from_options(&options, "dataContract")?;
        let data_contract: DataContract = data_contract_wasm.into();

        // Extract identity key from options
        let identity_key_wasm = IdentityPublicKeyWasm::try_from_options(&options, "identityKey")?;
        let identity_key: IdentityPublicKey = identity_key_wasm.into();

        // Extract signer from options
        let signer = IdentitySignerWasm::try_from_options(&options, "signer")?;

        // Extract settings from options
        let settings =
            try_from_options_optional::<PutSettingsInput>(&options, "settings")?.map(Into::into);

        // Create and broadcast the contract
        // Note: The SDK will set the actual contract ID based on the identity nonce
        let published_contract = data_contract
            .put_to_platform_and_wait_for_response(
                self.inner_sdk(),
                identity_key,
                &signer,
                settings,
            )
            .await?;

        // Add the published contract to the context provider cache
        // This is needed so that subsequent document operations can verify proofs
        self.add_contract_to_context_cache(&published_contract)?;

        Ok(published_contract.into())
    }
}

// ============================================================================
// Contract Update
// ============================================================================

/// TypeScript interface for contract update options
#[wasm_bindgen(typescript_custom_section)]
const CONTRACT_UPDATE_OPTIONS_TS: &'static str = r#"
/**
 * Options for updating an existing data contract on Dash Platform.
 */
export interface ContractUpdateOptions {
  /**
   * The updated data contract.
   * Use the existing contract and modify it, or create a new one with
   * `DataContract.fromJSON(...)`. Version must be incremented.
   */
  dataContract: DataContract;

  /**
   * The identity public key to use for signing the transition.
   * Get this from the owner identity's public keys.
   */
  identityKey: IdentityPublicKey;

  /**
   * Signer containing the private key that corresponds to the identity key.
   * Use IdentitySigner to add the private key before calling.
   */
  signer: IdentitySigner;

  /**
   * Optional settings for the broadcast operation.
   * Includes retries, timeouts, userFeeIncrease, etc.
   */
  settings?: PutSettings;
}
"#;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(typescript_type = "ContractUpdateOptions")]
    pub type ContractUpdateOptionsJs;
}

#[wasm_bindgen]
impl WasmSdk {
    /// Update an existing data contract on Dash Platform.
    ///
    /// This method handles the complete contract update flow:
    /// 1. Creates and signs the contract update transition
    /// 2. Broadcasts and waits for confirmation
    ///
    /// @param options - Update options including the updated data contract, public key, and signer
    /// @returns Promise that resolves when the contract is updated
    #[wasm_bindgen(js_name = "contractUpdate")]
    pub async fn contract_update(
        &self,
        options: ContractUpdateOptionsJs,
    ) -> Result<(), WasmSdkError> {
        // Extract data contract from options
        let data_contract_wasm = DataContractWasm::try_from_options(&options, "dataContract")?;
        let updated_contract: DataContract = data_contract_wasm.into();

        // Get identifiers from the contract
        let contract_id: Identifier = updated_contract.id();
        let owner_id: Identifier = updated_contract.owner_id();

        // Extract identity key from options
        let identity_key_wasm = IdentityPublicKeyWasm::try_from_options(&options, "identityKey")?;
        let identity_key: IdentityPublicKey = identity_key_wasm.into();

        // Extract signer from options
        let signer = IdentitySignerWasm::try_from_options(&options, "signer")?;

        // Extract settings from options
        let settings =
            try_from_options_optional::<PutSettingsInput>(&options, "settings")?.map(Into::into);

        // Get identity contract nonce
        let identity_contract_nonce = self
            .inner_sdk()
            .get_identity_contract_nonce(owner_id, contract_id, true, settings)
            .await?;

        // Create partial identity for signing
        let partial_identity = dash_sdk::dpp::identity::PartialIdentity {
            id: owner_id,
            loaded_public_keys: BTreeMap::from([(identity_key.id(), identity_key.clone())]),
            balance: None,
            revision: None,
            not_found_public_keys: Default::default(),
        };

        // Create the update transition
        let state_transition = DataContractUpdateTransition::new_from_data_contract(
            updated_contract.clone(),
            &partial_identity,
            identity_key.id(),
            identity_contract_nonce,
            get_user_fee_increase(settings.as_ref()),
            &signer,
            self.inner_sdk().version(),
            None,
        )
        .await
        .map_err(|e| WasmSdkError::generic(format!("Failed to create update transition: {}", e)))?;

        // Broadcast the transition. A contract update proof authenticates
        // the current contract body — a height-pinned snapshot — and cannot
        // bind this update's execution, so the snapshot wait is required.
        use dash_sdk::dpp::state_transition::proof_result::StateTransitionProofResult;
        state_transition
            .broadcast_and_wait_for_affected_state::<StateTransitionProofResult>(
                self.inner_sdk(),
                settings,
            )
            .await?;

        Ok(())
    }
}

// ============================================================================
// Contract User Moderation
// ============================================================================

#[wasm_bindgen(typescript_custom_section)]
const CONTRACT_MODERATION_OPTIONS_TS: &'static str = r#"
/**
 * Options for banning, unbanning, suspending or unsuspending one identity on a moderated data
 * contract (protocol version 14). The signer must hold a CRITICAL authentication key without
 * contract bounds of the moderating identity: the contract owner, or a moderator the contract's
 * config names.
 */
export interface ContractModerationOptions {
  /** The moderating identity: the contract owner or a named moderator */
  identity: Identity;
  /** The moderated contract */
  contractId: IdentifierLike;
  /** The identity to moderate */
  identityId: IdentifierLike;
  /** For a suspension: the block time, in milliseconds, at which it lapses */
  until?: bigint;
  /** Signer holding a CRITICAL authentication key without contract bounds of the identity */
  signer: IdentitySigner;
  /** Optional broadcast settings */
  settings?: PutSettings;
}

/**
 * The moderated identity's status on the lists the moderation touched, as its proof shows it.
 * A ban proves every list the contract keeps (it removes a suspension too); an unban, a
 * suspend and an unsuspend prove the one list they edit and say nothing about the other, so
 * after an unsuspend `banned` is undefined (unknown), not false. Use
 * `getContractModerationStatus` for the identity's whole status.
 */
export interface ContractModerationResult {
  contractId: Identifier;
  identityId: Identifier;
  /** The lists the proof covers, the only ones this result describes */
  lists: ContractModerationListKind[];
  /** Set when `lists` includes `banlist`: the identity is on the banlist */
  banned?: boolean;
  /**
   * When `lists` includes `suspensions`: the block time, in milliseconds, until which the
   * identity is suspended; undefined when it is not suspended
   */
  suspendedUntil?: bigint;
}
"#;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(typescript_type = "ContractModerationOptions")]
    pub type ContractModerationOptionsJs;

    #[wasm_bindgen(typescript_type = "ContractModerationResult")]
    pub type ContractModerationResultJs;
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContractModerationOptionsInput {
    #[serde(default)]
    until: Option<u64>,
}

impl WasmSdk {
    async fn moderate_contract_user(
        &self,
        options: ContractModerationOptionsJs,
        action: &str,
    ) -> Result<ContractModerationResultJs, WasmSdkError> {
        use dash_sdk::platform::transition::contract_user_moderation::ModerateContractUser;
        use wasm_dpp2::data_contract::moderation_action_from_parts;
        use wasm_dpp2::identity::IdentityWasm;
        use wasm_dpp2::IdentifierWasm;

        // Extract complex types first (borrows &options)
        let identity: dash_sdk::dpp::identity::Identity =
            IdentityWasm::try_from_options(&options, "identity")?.into();
        let contract_id: Identifier =
            IdentifierWasm::try_from_options(&options, "contractId")?.into();
        let identity_id: Identifier =
            IdentifierWasm::try_from_options(&options, "identityId")?.into();
        let signer = IdentitySignerWasm::try_from_options(&options, "signer")?;
        let settings =
            try_from_options_optional::<PutSettingsInput>(&options, "settings")?.map(Into::into);

        // Deserialize simple fields last (consumes options)
        let parsed: ContractModerationOptionsInput =
            crate::queries::utils::deserialize_required_query(
                options,
                "Options object is required",
                "contract moderation options",
            )?;

        let action = moderation_action_from_parts(action, identity_id, parsed.until)
            .map_err(|e| WasmSdkError::invalid_argument(e.to_string()))?;

        // The proof of a ban covers every list the contract keeps, which the verifier reads
        // from the contract, so the contract is resolved and cached before anything is paid
        // for; a cold cache would otherwise refuse a result the network already accepted.
        self.get_or_fetch_contract(contract_id).await?;

        let status = identity
            .moderate_contract_user(
                self.inner_sdk(),
                contract_id,
                action,
                None,
                signer,
                settings,
            )
            .await?;

        let result = js_sys::Object::new();
        let set = |key: &str, value: JsValue| {
            js_sys::Reflect::set(&result, &key.into(), &value).map_err(|_| {
                WasmSdkError::generic(format!("failed to set `{key}` on the moderation result"))
            })
        };
        set(
            "contractId",
            IdentifierWasm::from(status.contract_id).into(),
        )?;
        set(
            "identityId",
            IdentifierWasm::from(status.identity_id).into(),
        )?;
        // Only the lists proved are reported: a field for a list that was not proved stays
        // undefined (unknown) rather than reading as "not banned" or "not suspended".
        let lists = js_sys::Array::new();
        for list_status in &status.status.0 {
            match list_status {
                ContractModerationListStatus::Banlist { banned } => {
                    lists.push(&"banlist".into());
                    set("banned", (*banned).into())?;
                }
                ContractModerationListStatus::Suspensions { suspended_until } => {
                    lists.push(&"suspensions".into());
                    if let Some(until) = suspended_until {
                        set("suspendedUntil", js_sys::BigInt::from(*until).into())?;
                    }
                }
            }
        }
        set("lists", lists.into())?;
        Ok(JsValue::from(result).into())
    }
}

#[wasm_bindgen]
impl WasmSdk {
    /// Puts an identity on a moderated contract's banlist. A banned identity cannot act on the
    /// contract at the document level until it is unbanned.
    ///
    /// @param options - The moderating identity, the contract, the target and the signer
    /// @returns The target's status on the contract, proved
    #[wasm_bindgen(js_name = "contractBanUser")]
    pub async fn contract_ban_user(
        &self,
        options: ContractModerationOptionsJs,
    ) -> Result<ContractModerationResultJs, WasmSdkError> {
        self.moderate_contract_user(options, "ban").await
    }

    /// Takes an identity off a moderated contract's banlist.
    ///
    /// @param options - The moderating identity, the contract, the target and the signer
    /// @returns The target's status on the contract, proved
    #[wasm_bindgen(js_name = "contractUnbanUser")]
    pub async fn contract_unban_user(
        &self,
        options: ContractModerationOptionsJs,
    ) -> Result<ContractModerationResultJs, WasmSdkError> {
        self.moderate_contract_user(options, "unban").await
    }

    /// Suspends an identity on a moderated contract until the block time `until`, in
    /// milliseconds, replacing a suspension it already carries. The first document transition
    /// of the identity after the suspension lapses sweeps it.
    ///
    /// @param options - The moderating identity, the contract, the target, `until` and the signer
    /// @returns The target's status on the contract, proved
    #[wasm_bindgen(js_name = "contractSuspendUser")]
    pub async fn contract_suspend_user(
        &self,
        options: ContractModerationOptionsJs,
    ) -> Result<ContractModerationResultJs, WasmSdkError> {
        self.moderate_contract_user(options, "suspend").await
    }

    /// Takes an identity off a moderated contract's suspension list, lapsed or not.
    ///
    /// @param options - The moderating identity, the contract, the target and the signer
    /// @returns The target's status on the contract, proved
    #[wasm_bindgen(js_name = "contractUnsuspendUser")]
    pub async fn contract_unsuspend_user(
        &self,
        options: ContractModerationOptionsJs,
    ) -> Result<ContractModerationResultJs, WasmSdkError> {
        self.moderate_contract_user(options, "unsuspend").await
    }
}
