import Foundation
import SwiftData

// `PersistentDashpayIgnoredSender` exactly as schema DashSchemaV4 registered it, generated by
// scripts/freeze_schema_models.py from the live model at commit 787cac09e7.
// Do not edit: every stored property, its optionality and default, and
// every @Attribute / @Relationship / #Unique here is an input to that
// version's checksum, and every #Index to the store's SQLite indexes;
// changing any of them re-breaks the stores this copy exists to keep
// openable. See the live model for what each column means.
extension DashSchemaV4 {
    @Model
    final class PersistentDashpayIgnoredSender {
        #Unique<PersistentDashpayIgnoredSender>([
            \.networkRaw, \.ownerIdentityId, \.ignoredSenderId
        ])

        var networkRaw: UInt32

        var network: Network {
            get { Network(rawValue: networkRaw) ?? .testnet }
            set { networkRaw = newValue.rawValue }
        }

        var ownerIdentityId: Data

        var ignoredSenderId: Data

        var owner: PersistentIdentity

        var ignoredAt: Date

        init(
            owner: PersistentIdentity,
            ignoredSenderId: Data
        ) {
            self.owner = owner
            self.networkRaw = owner.networkRaw
            self.ownerIdentityId = owner.identityId
            self.ignoredSenderId = ignoredSenderId
            self.ignoredAt = Date()
        }
    }
}

extension DashSchemaV4.PersistentDashpayIgnoredSender {
    static func predicate(
        ownerIdentityId: Data
    ) -> Predicate<DashSchemaV4.PersistentDashpayIgnoredSender> {
        let target = ownerIdentityId
        return #Predicate<DashSchemaV4.PersistentDashpayIgnoredSender> { row in
            row.ownerIdentityId == target
        }
    }

    static func predicate(
        ownerIdentityId: Data,
        ignoredSenderId: Data
    ) -> Predicate<DashSchemaV4.PersistentDashpayIgnoredSender> {
        let target = ownerIdentityId
        let sender = ignoredSenderId
        return #Predicate<DashSchemaV4.PersistentDashpayIgnoredSender> { row in
            row.ownerIdentityId == target
                && row.ignoredSenderId == sender
        }
    }
}
