import Foundation
import SwiftData

// `PersistentTxo` exactly as schema DashSchemaV1 registered it, generated by
// scripts/freeze_schema_models.py from the live model at commit 96a103375e.
// Do not edit: every stored property, its optionality and default, and
// every @Attribute / @Relationship / #Index / #Unique here is an input to
// that version's checksum, and changing any of them re-breaks the stores
// this copy exists to keep openable. See the live model for what each
// column means.
extension DashSchemaV1 {
    @Model
    final class PersistentTxo {
        #Index<PersistentTxo>([\.walletId])

        @Attribute(.unique) var outpoint: Data
        var vout: UInt32
        var amount: UInt64
        var address: String
        var scriptPubKey: Data
        var height: UInt32
        var isCoinbase: Bool
        var isConfirmed: Bool
        var isInstantLocked: Bool
        var isLocked: Bool
        var isSpent: Bool
        var createdAt: Date
        var lastUpdated: Date

        var walletId: Data = Data()

        var transaction: PersistentTransaction?

        var spendingTransaction: PersistentTransaction?

        var spendingInputIndex: UInt32? = nil

        var account: PersistentAccount?

        var coreAddress: PersistentCoreAddress?

        init(
            transaction: PersistentTransaction,
            vout: UInt32,
            amount: UInt64,
            address: String,
            scriptPubKey: Data = Data(),
            height: UInt32 = 0
        ) {
            self.outpoint = Self.makeOutpoint(txid: transaction.txid, vout: vout)
            self.vout = vout
            self.amount = amount
            self.address = address
            self.scriptPubKey = scriptPubKey
            self.height = height
            self.isCoinbase = false
            self.isConfirmed = false
            self.isInstantLocked = false
            self.isLocked = false
            self.isSpent = false
            self.createdAt = Date()
            self.lastUpdated = Date()
            self.transaction = transaction
        }

        static func makeOutpoint(txid: Data, vout: UInt32) -> Data {
            var data = Data(capacity: 36)
            data.append(txid)
            var v = vout.littleEndian
            withUnsafeBytes(of: &v) { data.append(contentsOf: $0) }
            return data
        }

        var txid: Data {
            if let transaction {
                return transaction.txid
            }
            return outpoint.count >= 32 ? Data(outpoint.prefix(32)) : Data()
        }

        var txidHex: String {
            let rawTxid = txid
            guard rawTxid.count == 32 else { return "" }
            return rawTxid.reversed().map { String(format: "%02x", $0) }.joined()
        }

        var outpointHex: String {
            let hex = txidHex
            return hex.isEmpty ? "" : "\(hex):\(vout)"
        }

        var formattedAmount: String {
            let dash = Double(amount) / 100_000_000.0
            return String(format: "%.8f DASH", dash)
        }
    }
}
