import Foundation
import SwiftData

// `PersistentIdentity` exactly as schema DashSchemaV1 registered it, generated by
// scripts/freeze_schema_models.py from the live model at commit 5f58417079.
// Do not edit: every stored property, its optionality and default, and
// every @Attribute / @Relationship / #Unique here is an input to that
// version's checksum, and every #Index to the store's SQLite indexes;
// changing any of them re-breaks the stores this copy exists to keep
// openable. See the live model for what each column means.
extension DashSchemaV1 {
    @Model
    final class PersistentIdentity {
        #Index<PersistentIdentity>([\.networkRaw])

        @Attribute(.unique) var identityId: Data
        var balance: Int64
        var revision: Int64
        var isLocal: Bool
        var alias: String?
        var dpnsName: String?
        var mainDpnsName: String?
        var identityType: String

        var votingPrivateKeyIdentifier: String?
        var ownerPrivateKeyIdentifier: String?
        var payoutPrivateKeyIdentifier: String?

        @Relationship(deleteRule: .cascade) var publicKeys: [PersistentPublicKey]

        var createdAt: Date
        var lastUpdated: Date
        var lastSyncedAt: Date?

        var networkRaw: UInt32

        var network: Network {
            get { Network(rawValue: networkRaw) ?? .testnet }
            set { networkRaw = newValue.rawValue }
        }

        var wallet: PersistentWallet?
        var identityIndex: UInt32 = 0

        @Relationship(deleteRule: .cascade, inverse: \PersistentDocument.ownerIdentity) var documents: [PersistentDocument]
        @Relationship(deleteRule: .nullify) var tokenBalances: [PersistentTokenBalance]

        @Relationship(deleteRule: .cascade, inverse: \PersistentDPNSName.identity)
        var dpnsNames: [PersistentDPNSName] = []

        @Relationship(deleteRule: .cascade, inverse: \PersistentDashpayProfile.identity)
        var dashpayProfile: PersistentDashpayProfile?

        @Relationship(deleteRule: .cascade, inverse: \PersistentDashpayContactRequest.owner)
        var contactRequests: [PersistentDashpayContactRequest] = []

        @Relationship(deleteRule: .cascade, inverse: \PersistentDashpayPayment.owner)
        var dashpayPayments: [PersistentDashpayPayment] = []

        @Relationship(deleteRule: .cascade, inverse: \PersistentDashpayIgnoredSender.owner)
        var dashpayIgnoredSenders: [PersistentDashpayIgnoredSender] = []

        @Relationship(deleteRule: .cascade, inverse: \PersistentDashpayContactProfile.owner)
        var contactProfiles: [PersistentDashpayContactProfile] = []

        var ownedDataContracts: [PersistentDataContract]

        init(
            identityId: Data,
            balance: Int64 = 0,
            revision: Int64 = 0,
            isLocal: Bool = true,
            alias: String? = nil,
            dpnsName: String? = nil,
            mainDpnsName: String? = nil,
            identityType: IdentityType = .user,
            votingPrivateKeyIdentifier: String? = nil,
            ownerPrivateKeyIdentifier: String? = nil,
            payoutPrivateKeyIdentifier: String? = nil,
            network: Network,
            identityIndex: UInt32 = 0
        ) {
            self.identityId = identityId
            self.balance = balance
            self.revision = revision
            self.isLocal = isLocal
            self.alias = alias
            self.dpnsName = dpnsName
            self.mainDpnsName = mainDpnsName
            self.identityType = identityType.rawValue
            self.votingPrivateKeyIdentifier = votingPrivateKeyIdentifier
            self.ownerPrivateKeyIdentifier = ownerPrivateKeyIdentifier
            self.payoutPrivateKeyIdentifier = payoutPrivateKeyIdentifier
            self.networkRaw = network.rawValue
            self.identityIndex = identityIndex
            self.publicKeys = []
            self.documents = []
            self.tokenBalances = []
            self.dpnsNames = []
            self.dashpayProfile = nil
            self.contactRequests = []
            self.dashpayPayments = []
            self.dashpayIgnoredSenders = []
            self.contactProfiles = []
            self.ownedDataContracts = []
            self.createdAt = Date()
            self.lastUpdated = Date()
            self.lastSyncedAt = nil
        }

        var identityIdString: String {
            identityId.toHexString()
        }

        var identityIdBase58: String {
            identityId.toBase58String()
        }

        var formattedBalance: String {
            let dashAmount = Double(balance) / 100_000_000_000
            return String(format: "%.8f DASH", dashAmount)
        }

        var identityPublicKeys: [IdentityPublicKey] {
            publicKeys.compactMap { $0.toIdentityPublicKey() }
        }

        var displayName: String {
            if let alias = alias, !alias.isEmpty {
                return alias
            }
            if let mainDpnsName = mainDpnsName, !mainDpnsName.isEmpty {
                return mainDpnsName
            }
            if let dpnsName = dpnsName, !dpnsName.isEmpty {
                return dpnsName
            }
            return String(identityIdString.prefix(12)) + "..."
        }

        var identityTypeEnum: IdentityType {
            IdentityType(rawValue: identityType) ?? .user
        }

        func updateBalance(_ newBalance: Int64) {
            self.balance = newBalance
            self.lastUpdated = Date()
        }

        func updateRevision(_ newRevision: Int64) {
            self.revision = newRevision
            self.lastUpdated = Date()
        }

        func markAsSynced() {
            self.lastSyncedAt = Date()
        }

        func updateDPNSName(_ name: String?) {
            self.dpnsName = name
            self.lastUpdated = Date()
        }

        func addPublicKey(_ key: PersistentPublicKey) {
            publicKeys.append(key)
            lastUpdated = Date()
        }

        func removePublicKey(withId keyId: Int32) {
            publicKeys.removeAll { $0.keyId == keyId }
            lastUpdated = Date()
        }
    }
}

extension DashSchemaV1.PersistentIdentity {
    static func predicate(identityId: Data) -> Predicate<DashSchemaV1.PersistentIdentity> {
        #Predicate<DashSchemaV1.PersistentIdentity> { identity in
            identity.identityId == identityId
        }
    }

    static var walletOwnedIdentitiesPredicate: Predicate<DashSchemaV1.PersistentIdentity> {
        #Predicate<DashSchemaV1.PersistentIdentity> { identity in
            identity.wallet != nil
        }
    }

    static func predicate(type: IdentityType) -> Predicate<DashSchemaV1.PersistentIdentity> {
        let typeString = type.rawValue
        return #Predicate<DashSchemaV1.PersistentIdentity> { identity in
            identity.identityType == typeString
        }
    }

    static func needsSyncPredicate(olderThan date: Date) -> Predicate<DashSchemaV1.PersistentIdentity> {
        #Predicate<DashSchemaV1.PersistentIdentity> { identity in
            identity.lastSyncedAt == nil || identity.lastSyncedAt! < date
        }
    }

    static func predicate(network: Network) -> Predicate<DashSchemaV1.PersistentIdentity> {
        let target = network.rawValue
        return #Predicate<DashSchemaV1.PersistentIdentity> { identity in
            identity.networkRaw == target
        }
    }

    static func walletOwnedIdentitiesPredicate(network: Network) -> Predicate<DashSchemaV1.PersistentIdentity> {
        let target = network.rawValue
        return #Predicate<DashSchemaV1.PersistentIdentity> { identity in
            identity.wallet != nil && identity.networkRaw == target
        }
    }

    static func fetch(
        in context: ModelContext,
        identityId: Data
    ) -> DashSchemaV1.PersistentIdentity? {
        let target = identityId
        let descriptor = FetchDescriptor<DashSchemaV1.PersistentIdentity>(
            predicate: #Predicate { $0.identityId == target }
        )
        return try? context.fetch(descriptor).first
    }
}

extension DashSchemaV1.PersistentIdentity {
    @discardableResult
    static func updateBalance(
        in context: ModelContext,
        identityId: Data,
        balance: UInt64
    ) -> Bool {
        guard let row = fetch(in: context, identityId: identityId) else { return false }
        row.balance = Int64(bitPattern: balance)
        row.lastUpdated = Date()
        return true
    }

    @discardableResult
    static func updateDpnsName(
        in context: ModelContext,
        identityId: Data,
        dpnsName: String?
    ) -> Bool {
        guard let row = fetch(in: context, identityId: identityId) else { return false }
        row.dpnsName = dpnsName
        row.lastUpdated = Date()
        return true
    }

    @discardableResult
    static func updateMainDpnsName(
        in context: ModelContext,
        identityId: Data,
        mainDpnsName: String?
    ) -> Bool {
        guard let row = fetch(in: context, identityId: identityId) else { return false }
        row.mainDpnsName = mainDpnsName
        row.lastUpdated = Date()
        return true
    }

    @discardableResult
    static func remove(
        in context: ModelContext,
        identityId: Data
    ) -> Bool {
        guard let row = fetch(in: context, identityId: identityId) else { return false }
        context.delete(row)
        return true
    }
}
