import Foundation
import SwiftData

// `PersistentPlatformAddressesSyncState` exactly as schema DashSchemaV1 registered it, generated by
// scripts/freeze_schema_models.py from the live model at commit 5f58417079.
// Do not edit: every stored property, its optionality and default, and
// every @Attribute / @Relationship / #Unique here is an input to that
// version's checksum, and every #Index to the store's SQLite indexes;
// changing any of them re-breaks the stores this copy exists to keep
// openable. See the live model for what each column means.
extension DashSchemaV1 {
    @Model
    final class PersistentPlatformAddressesSyncState {
        @Attribute(.unique) var walletId: Data
        var networkRaw: UInt32

        var network: Network {
            get { Network(rawValue: networkRaw) ?? .testnet }
            set { networkRaw = newValue.rawValue }
        }
        var syncHeight: UInt64
        var syncTimestamp: UInt64
        var lastKnownRecentBlock: UInt64
        var lastUpdated: Date

        init(
            walletId: Data,
            network: Network,
            syncHeight: UInt64,
            syncTimestamp: UInt64,
            lastKnownRecentBlock: UInt64
        ) {
            self.walletId = walletId
            self.networkRaw = network.rawValue
            self.syncHeight = syncHeight
            self.syncTimestamp = syncTimestamp
            self.lastKnownRecentBlock = lastKnownRecentBlock
            self.lastUpdated = Date()
        }
    }
}
