import Foundation
import SwiftData

// `PersistentWalletManagerMetadata` exactly as schema DashSchemaV1 registered it, generated by
// scripts/freeze_schema_models.py from the live model at commit 96a103375e.
// Do not edit: every stored property, its optionality and default, and
// every @Attribute / @Relationship / #Index / #Unique here is an input to
// that version's checksum, and changing any of them re-breaks the stores
// this copy exists to keep openable. See the live model for what each
// column means.
extension DashSchemaV1 {
    @Model
    final class PersistentWalletManagerMetadata {
        @Attribute(.unique) var networkRaw: UInt32
        var combinedSyncHeight: UInt32
        var combinedSyncBlockHash: Data?
        var walletCount: Int
        var createdAt: Date
        var lastUpdated: Date

        var network: Network {
            get { Network(rawValue: networkRaw) ?? .testnet }
            set { networkRaw = newValue.rawValue }
        }

        init(network: Network) {
            self.networkRaw = network.rawValue
            self.combinedSyncHeight = 0
            self.walletCount = 0
            self.createdAt = Date()
            self.lastUpdated = Date()
        }
    }
}
