import Foundation
import SwiftData

// `PersistentShieldedNote` exactly as schema DashSchemaV5 registered it, generated by
// scripts/freeze_schema_models.py from the live model at commit ba01d4cdfa.
// Do not edit: every stored property, its optionality and default, and
// every @Attribute / @Relationship / #Unique here is an input to that
// version's checksum, and every #Index to the store's SQLite indexes;
// changing any of them re-breaks the stores this copy exists to keep
// openable. See the live model for what each column means.
extension DashSchemaV5 {
    @Model
    final class PersistentShieldedNote {
        #Index<PersistentShieldedNote>([\.walletId, \.accountIndex])

        var walletId: Data
        var accountIndex: UInt32
        var position: UInt64
        var cmx: Data
        @Attribute(.unique) var nullifier: Data
        var blockHeight: UInt64
        var isSpent: Bool
        var value: UInt64
        var noteData: Data

        var createdAt: Date
        var lastUpdated: Date

        init(
            walletId: Data,
            accountIndex: UInt32,
            position: UInt64,
            cmx: Data,
            nullifier: Data,
            blockHeight: UInt64,
            isSpent: Bool,
            value: UInt64,
            noteData: Data
        ) {
            self.walletId = walletId
            self.accountIndex = accountIndex
            self.position = position
            self.cmx = cmx
            self.nullifier = nullifier
            self.blockHeight = blockHeight
            self.isSpent = isSpent
            self.value = value
            self.noteData = noteData
            let now = Date()
            self.createdAt = now
            self.lastUpdated = now
        }
    }
}

extension DashSchemaV5.PersistentShieldedNote {
    static func unspentPredicate(walletId: Data) -> Predicate<DashSchemaV5.PersistentShieldedNote> {
        #Predicate<DashSchemaV5.PersistentShieldedNote> {
            $0.walletId == walletId && $0.isSpent == false
        }
    }

    static var unspentPredicate: Predicate<DashSchemaV5.PersistentShieldedNote> {
        #Predicate<DashSchemaV5.PersistentShieldedNote> { $0.isSpent == false }
    }
}
