use dapi_grpc::platform::v0::{Proof, ResponseMetadata};
use dpp::bls_signatures;

use crate::Error;
use dpp::bls_signatures::{Bls12381G2Impl, Pairing, Signature};
use tenderdash_abci::{
    proto::types::{CanonicalVote, SignedMsgType, StateId},
    signatures::{Hashable, Signable},
};

use crate::ContextProvider;

/// Verify cryptographic proof generated by Tenderdash
///
/// This function verifies the cryptographic proof generated by Tenderdash.
/// It verifies the signature of the proof using the public key of the quorum.
///
/// ## Parameters
///
/// - `proof`: The cryptographic proof generated by Tenderdash
/// - `mtd`: The metadata of the response from Dash Platform
/// - `root_hash`: The root hash of the response from Dash Platform
/// - `provider`: The provider of quorum information
///
/// ## Returns
///
/// Returns:
/// * `Ok(())` when the proof is valid
/// * `Err(Error)` when the proof is invalid
///
pub(crate) fn verify_tenderdash_proof(
    proof: &Proof,
    mtd: &ResponseMetadata,
    root_hash: &[u8],
    provider: &dyn ContextProvider,
) -> Result<(), Error> {
    let block_id_hash = proof.block_id_hash.to_vec();

    let version = mtd.protocol_version as u64;
    let height = mtd.height;
    let round = proof.round;
    let core_locked_height = mtd.core_chain_locked_height;
    let quorum_hash = TryInto::<[u8; 32]>::try_into(proof.quorum_hash.as_slice()).map_err(|e| {
        Error::ResponseDecodeError {
            error: "invalid quorum hash size: ".to_string() + &e.to_string(),
        }
    })?;

    // Now, lookup quorum details
    let chain_id = mtd.chain_id.clone();
    let quorum_type = proof.quorum_type;
    let pubkey_bytes =
        provider.get_quorum_public_key(quorum_type, quorum_hash, core_locked_height)?;

    let state_id = StateId {
        app_version: version,
        core_chain_locked_height: mtd.core_chain_locked_height,
        time: mtd.time_ms,
        app_hash: root_hash.into(),
        height,
    };

    let state_id_hash = state_id
        .calculate_msg_hash(&chain_id, mtd.height as i64, proof.round as i32)
        .map_err(|e| Error::ResponseDecodeError {
            error: format!("failed to calculate state id hash: {}", e),
        })?;

    let commit = CanonicalVote {
        r#type: SignedMsgType::Precommit.into(),
        block_id: block_id_hash,
        chain_id: chain_id.clone(),
        height: mtd.height as i64,
        round: proof.round as i64,
        state_id: state_id_hash,
    };

    // Verify signature
    let sign_digest = commit
        .calculate_sign_hash(
            &chain_id,
            quorum_type
                .try_into()
                .map_err(|_| Error::ResponseDecodeError {
                    error: format!("quorum type out of range: {}", quorum_type),
                })?,
            &quorum_hash,
            height as i64,
            round as i32,
        )
        .map_err(|e| Error::SignDigestFailed {
            error: e.to_string(),
        })?;

    let signature = TryInto::<[u8; 96]>::try_into(proof.signature.as_slice()).map_err(|e| {
        Error::InvalidSignatureFormat {
            error: "invalid signature size: ".to_string() + &e.to_string(),
        }
    })?;

    let pubkey = bls_signatures::PublicKey::<Bls12381G2Impl>::try_from(pubkey_bytes.as_slice())
        .map_err(|e| Error::InvalidPublicKey {
            error: e.to_string(),
        })?;

    tracing::trace!(
        ?state_id,
        signature = hex::encode(signature),
        sign_digest = hex::encode(&sign_digest),
        ?pubkey,
        "verify signature"
    );

    match verify_signature_digest(&sign_digest, &signature, &pubkey)? {
        true => Ok(()),
        false => Err(Error::InvalidSignature {
            error: format!(
                "signature {} could not be verified with public key {} for sign digest {}",
                hex::encode(signature),
                hex::encode(pubkey_bytes),
                hex::encode(sign_digest)
            ),
        }),
    }
}

/// Verify signature for [sign_digest](tenderdash_abci::signatures::SignDigest), using provided `public_key`
pub fn verify_signature_digest(
    sign_digest: &[u8],
    signature: &[u8; 96],
    public_key: &bls_signatures::PublicKey<Bls12381G2Impl>,
) -> Result<bool, Error> {
    if signature == &[0; 96] {
        return Err(Error::SignatureVerificationError {
            error: "empty signature".to_string(),
        });
    }
    let signature = Signature::Basic(
        <Bls12381G2Impl as Pairing>::Signature::from_compressed(signature)
            .into_option()
            .ok_or(Error::SignatureVerificationError {
                error: "Could not verify signature digest".to_string(),
            })?,
    );

    Ok(signature.verify(public_key, sign_digest).is_ok())
}

#[cfg(test)]
mod tests {
    use super::*;
    use dapi_grpc::platform::v0::{Proof, ResponseMetadata};
    use dash_context_provider::ContextProviderError;
    use dpp::data_contract::TokenConfiguration;
    use dpp::prelude::{CoreBlockHeight, DataContract, Identifier};
    use dpp::version::PlatformVersion;
    use std::sync::Arc;

    /// Minimal ContextProvider stub that returns a dummy quorum public key.
    /// This allows the test to reach the vulnerable `.expect()` on line 80
    /// without failing earlier in the verification pipeline.
    struct StubContextProvider;

    impl ContextProvider for StubContextProvider {
        fn get_data_contract(
            &self,
            _id: &Identifier,
            _platform_version: &PlatformVersion,
        ) -> Result<Option<Arc<DataContract>>, ContextProviderError> {
            Ok(None)
        }

        fn get_token_configuration(
            &self,
            _token_id: &Identifier,
        ) -> Result<Option<TokenConfiguration>, ContextProviderError> {
            Ok(None)
        }

        fn get_quorum_public_key(
            &self,
            _quorum_type: u32,
            _quorum_hash: [u8; 32],
            _core_chain_locked_height: u32,
        ) -> Result<[u8; 48], ContextProviderError> {
            // Return a dummy 48-byte public key; it does not need to be
            // cryptographically valid because the panic occurs before the
            // signature check.
            Ok([0u8; 48])
        }

        fn get_platform_activation_height(&self) -> Result<CoreBlockHeight, ContextProviderError> {
            Ok(1)
        }
    }

    /// Verify that an out-of-range `quorum_type` from a malicious node
    /// returns an error instead of panicking.
    ///
    /// `verify_tenderdash_proof` receives `quorum_type` as a `u32` from an
    /// untrusted gRPC response and converts it to `u8`. Any value > 255
    /// must produce an `Err`, not a panic.
    #[test]
    fn test_malicious_quorum_type_returns_error() {
        let proof = Proof {
            grovedb_proof: vec![],
            quorum_hash: vec![0u8; 32], // valid 32-byte hash so we pass the earlier check
            signature: vec![0u8; 96],
            round: 1,
            block_id_hash: vec![0u8; 32],
            quorum_type: u32::MAX, // out-of-range: cannot fit in u8
        };

        let metadata = ResponseMetadata {
            height: 100,
            core_chain_locked_height: 1,
            epoch: 0,
            time_ms: 1_000_000,
            protocol_version: 1,
            chain_id: "test-chain".to_string(),
        };

        let provider = StubContextProvider;

        let result = verify_tenderdash_proof(&proof, &metadata, &[0u8; 32], &provider);
        let err = result.expect_err("expected error for out-of-range quorum_type");
        let err_msg = err.to_string();
        assert!(
            err_msg.contains("quorum type out of range"),
            "error message should mention quorum type out of range, got: {err_msg}"
        );
    }

    /// Helper: create a deterministic BLS key pair for testing.
    fn test_keypair() -> (
        bls_signatures::SecretKey<Bls12381G2Impl>,
        bls_signatures::PublicKey<Bls12381G2Impl>,
    ) {
        let sk = bls_signatures::SecretKey::<Bls12381G2Impl>::from_hash(b"test-key-seed");
        let pk = sk.public_key();
        (sk, pk)
    }

    /// A ContextProvider that returns a cryptographically valid public key
    /// so that tests can progress past the public-key parsing step and
    /// reach deeper code paths (e.g. signature verification).
    struct ValidKeyContextProvider {
        pubkey_bytes: [u8; 48],
    }

    impl ValidKeyContextProvider {
        fn new() -> Self {
            let (_, pk) = test_keypair();
            let pk_vec: Vec<u8> = (&pk).into();
            let mut pubkey_bytes = [0u8; 48];
            pubkey_bytes.copy_from_slice(&pk_vec);
            Self { pubkey_bytes }
        }
    }

    impl ContextProvider for ValidKeyContextProvider {
        fn get_data_contract(
            &self,
            _id: &Identifier,
            _platform_version: &PlatformVersion,
        ) -> Result<Option<Arc<DataContract>>, ContextProviderError> {
            Ok(None)
        }

        fn get_token_configuration(
            &self,
            _token_id: &Identifier,
        ) -> Result<Option<TokenConfiguration>, ContextProviderError> {
            Ok(None)
        }

        fn get_quorum_public_key(
            &self,
            _quorum_type: u32,
            _quorum_hash: [u8; 32],
            _core_chain_locked_height: u32,
        ) -> Result<[u8; 48], ContextProviderError> {
            Ok(self.pubkey_bytes)
        }

        fn get_platform_activation_height(&self) -> Result<CoreBlockHeight, ContextProviderError> {
            Ok(1)
        }
    }

    /// Helper to build default test metadata.
    fn test_metadata() -> ResponseMetadata {
        ResponseMetadata {
            height: 100,
            core_chain_locked_height: 1,
            epoch: 0,
            time_ms: 1_000_000,
            protocol_version: 1,
            chain_id: "test-chain".to_string(),
        }
    }

    /// An all-zeros 96-byte signature must be rejected early by
    /// `verify_signature_digest` with a `SignatureVerificationError`
    /// containing "empty signature".
    #[test]
    fn test_verify_signature_digest_all_zeros() {
        let (_, pk) = test_keypair();
        let sign_digest = b"some-digest-data";
        let signature = [0u8; 96];

        let result = verify_signature_digest(sign_digest, &signature, &pk);
        let err = result.expect_err("expected error for all-zero signature");
        let err_msg = err.to_string();
        assert!(
            err_msg.contains("empty signature"),
            "error should mention empty signature, got: {err_msg}"
        );
    }

    /// Random non-zero 96 bytes that do not form a valid compressed BLS
    /// signature must cause `verify_signature_digest` to return
    /// `SignatureVerificationError`.
    #[test]
    fn test_verify_signature_digest_invalid_compressed() {
        let (_, pk) = test_keypair();
        let sign_digest = b"some-digest-data";

        // Construct 96 non-zero bytes that are not a valid BLS signature.
        // We use a simple pattern that is extremely unlikely to be a valid
        // compressed G2 point.
        let mut signature = [0xFFu8; 96];
        signature[0] = 0x01; // ensure it is not all-0xFF either

        let result = verify_signature_digest(sign_digest, &signature, &pk);
        let err = result.expect_err("expected error for invalid compressed signature");
        let err_msg = err.to_string();
        assert!(
            err_msg.contains("Could not verify signature digest"),
            "error should mention failed verification, got: {err_msg}"
        );
    }

    /// A `Proof` whose `quorum_hash` is not exactly 32 bytes must
    /// produce a `ResponseDecodeError` mentioning "invalid quorum hash
    /// size".
    #[test]
    fn test_verify_tenderdash_proof_invalid_quorum_hash_size() {
        let proof = Proof {
            grovedb_proof: vec![],
            quorum_hash: vec![0u8; 16], // too short — not 32 bytes
            signature: vec![0u8; 96],
            round: 1,
            block_id_hash: vec![0u8; 32],
            quorum_type: 1,
        };

        let metadata = test_metadata();
        let provider = StubContextProvider;

        let result = verify_tenderdash_proof(&proof, &metadata, &[0u8; 32], &provider);
        let err = result.expect_err("expected error for invalid quorum hash size");
        let err_msg = err.to_string();
        assert!(
            err_msg.contains("invalid quorum hash size"),
            "error should mention invalid quorum hash size, got: {err_msg}"
        );
    }

    /// A `Proof` with a valid 32-byte `quorum_hash` but a signature
    /// that is not exactly 96 bytes must produce an
    /// `InvalidSignatureFormat` error mentioning "invalid signature
    /// size".
    #[test]
    fn test_verify_tenderdash_proof_invalid_signature_size() {
        let proof = Proof {
            grovedb_proof: vec![],
            quorum_hash: vec![0u8; 32],
            signature: vec![0u8; 50], // wrong size — not 96 bytes
            round: 1,
            block_id_hash: vec![0u8; 32],
            quorum_type: 1,
        };

        let metadata = test_metadata();
        let provider = ValidKeyContextProvider::new();

        let result = verify_tenderdash_proof(&proof, &metadata, &[0u8; 32], &provider);
        let err = result.expect_err("expected error for invalid signature size");
        let err_msg = err.to_string();
        assert!(
            err_msg.contains("invalid signature size"),
            "error should mention invalid signature size, got: {err_msg}"
        );
    }

    /// A `Proof` with 96 zero-byte signature that reaches
    /// `verify_signature_digest` through `verify_tenderdash_proof` must
    /// trigger the "empty signature" early-return error.
    #[test]
    fn test_verify_tenderdash_proof_empty_signature() {
        let proof = Proof {
            grovedb_proof: vec![],
            quorum_hash: vec![0u8; 32],
            signature: vec![0u8; 96], // all zeros — "empty signature"
            round: 1,
            block_id_hash: vec![0u8; 32],
            quorum_type: 1,
        };

        let metadata = test_metadata();
        let provider = ValidKeyContextProvider::new();

        let result = verify_tenderdash_proof(&proof, &metadata, &[0u8; 32], &provider);
        let err = result.expect_err("expected error for empty signature");
        let err_msg = err.to_string();
        assert!(
            err_msg.contains("empty signature"),
            "error should mention empty signature, got: {err_msg}"
        );
    }
}
