use crate::version::drive_versions::drive_grove_method_versions::{
    DriveGroveApplyMethodVersions, DriveGroveBasicMethodVersions, DriveGroveBatchMethodVersions,
    DriveGroveCostMethodVersions, DriveGroveMethodVersions,
};

pub const DRIVE_GROVE_METHOD_VERSIONS_V1: DriveGroveMethodVersions = DriveGroveMethodVersions {
    basic: DriveGroveBasicMethodVersions {
        grove_insert: 0,
        grove_insert_empty_tree: 0,
        grove_insert_empty_sum_tree: 0,
        grove_insert_if_not_exists: 0,
        grove_insert_if_not_exists_return_existing_element: 0,
        grove_clear: 0,
        grove_delete: 0,
        grove_get_raw: 0,
        grove_get_raw_optional: 0,
        grove_get_raw_value_u64_from_encoded_var_vec: 0,
        grove_get: 0,
        grove_get_path_query_serialized_results: 0,
        grove_get_path_query_serialized_or_sum_results: 0,
        grove_get_path_query: 0,
        grove_get_path_query_with_optional: 0,
        grove_get_raw_path_query_with_optional: 0,
        grove_get_raw_path_query: 0,
        grove_get_proved_path_query: 0,
        grove_get_proved_path_query_with_conditional: 0,
        grove_get_sum_tree_total_value: 0,
        grove_has_raw: 0,
        grove_get_raw_item: 0,
        grove_get_optional_sum_tree_total_value: 0,
        grove_get_raw_optional_item: 0,
        grove_get_big_sum_tree_total_value: 0,
    },
    batch: DriveGroveBatchMethodVersions {
        batch_insert_empty_tree: 0,
        batch_insert_empty_tree_if_not_exists: 0,
        batch_insert_empty_tree_if_not_exists_check_existing_operations: 0,
        batch_insert_sum_item_if_not_exists: 0,
        batch_insert_sum_item_or_add_to_if_already_exists: 0,
        batch_insert: 0,
        batch_insert_if_not_exists: 0,
        batch_insert_if_changed_value: 0,
        batch_replace: 0,
        batch_delete: 0,
        batch_delete_items_in_path_query: 0,
        batch_move_items_in_path_query: 0,
        batch_remove_raw: 0,
        batch_delete_up_tree_while_empty: 0,
        batch_refresh_reference: 0,
        batch_insert_empty_sum_tree: 0,
        batch_move: 0,
    },
    apply: DriveGroveApplyMethodVersions {
        grove_apply_operation: 0,
        grove_apply_batch: 0,
        grove_apply_partial_batch: 0,
    },
    costs: DriveGroveCostMethodVersions {
        grove_batch_operations_costs: 0,
    },
};
