import SwiftData
import XCTest

@testable import SwiftDashSDK

/// Coverage for the protocol-version-14 `propertyConstraints` bridge: the
/// decoding of what `dash_sdk_data_contract_get_property_constraints` and
/// `dash_sdk_data_contract_check_property_constraints` return, and the
/// wrappers' round trip through the FFI.
///
/// Rust parses and evaluates the rules (rs-sdk-ffi's own tests cover every
/// rule family and violation); the Swift side only marshals, so these tests pin
/// the JSON shapes, which match wasm-dpp2's key for key, and the marshalling.
/// The round trips run on the FFI mock SDK, which sits at a protocol version
/// below 14, where no document type carries a rule.
@MainActor
final class DocumentPropertyConstraintsTests: XCTestCase {

    /// The rules of an `offer` type as the FFI reports them (rs-sdk-ffi's
    /// `should_list_every_rule_in_name_order_with_what_it_reads`), abridged to
    /// three rules.
    private let rulesJSON = """
        [
          {
            "name": "closedNeedsClosedAt",
            "readsOwner": false,
            "reads": [
              { "kind": "text", "path": "status" },
              { "kind": "presence", "path": "closedAt" }
            ],
            "rule": {
              "anyOf": [
                { "notEqual": ["status", { "const": "closed" }] },
                { "present": "closedAt" }
              ]
            }
          },
          {
            "name": "perUnitFee",
            "readsOwner": false,
            "reads": [
              { "kind": "value", "path": "price" },
              { "kind": "value", "path": "fee" }
            ],
            "rule": { "greaterThanOrEqual": [{ "divide": ["price", "fee"] }, 1] }
          },
          {
            "name": "sellerIsOwner",
            "readsOwner": true,
            "reads": [
              { "kind": "presence", "path": "sellerId" },
              { "kind": "identifier", "path": "sellerId" }
            ],
            "rule": {
              "anyOf": [{ "absent": "sellerId" }, { "equal": ["sellerId", "$ownerId"] }]
            }
          }
        ]
        """

    /// The platform serialization of a contract created at protocol version
    /// 13, owned by `[7; 32]`, declaring one `note` type with a string
    /// `message` and no rules (generated by rs-sdk-ffi's
    /// `serialize_to_bytes_with_platform_version`). It reads at every later
    /// protocol version too.
    private let noteContractHex =
        "013ac40651a4bcb91c3f5c1e458a1c95e48dc2c8259003dd580cab11a5f02ed4850100000000010100000101070707070707"
        + "07070707070707070707070707070707070707070707070707070001046e6f7465160312047479706512066f626a65637412"
        + "0a70726f70657274696573160112076d65737361676516031204747970651206737472696e6712096d61784c656e67746805"
        + "801208706f736974696f6e050012146164646974696f6e616c50726f70657274696573130000000000000000000000"

    private let ownerId = Data(repeating: 7, count: 32)

    // MARK: - Rules

    func testRulesDecodeInOrderWithWhatTheyRead() throws {
        let rules = try DocumentPropertyConstraint.list(fromJSON: rulesJSON)

        XCTAssertEqual(rules.map(\.name), ["closedNeedsClosedAt", "perUnitFee", "sellerIsOwner"])
        XCTAssertEqual(
            rules[0].reads,
            [
                PropertyConstraintRead(path: "status", kind: .text),
                PropertyConstraintRead(path: "closedAt", kind: .presence)
            ]
        )
        XCTAssertEqual(rules[1].reads.map(\.kind), [.value, .value])
        XCTAssertEqual(rules[2].reads.map(\.kind), [.presence, .identifier])
        XCTAssertEqual(rules.map(\.readsOwner), [false, false, true])
    }

    /// The rule is kept as the JSON the schema declares, compact with sorted
    /// keys: array order, and so operand order, is untouched.
    func testRuleIsKeptAsDeclaredJSON() throws {
        let rules = try DocumentPropertyConstraint.list(fromJSON: rulesJSON)

        XCTAssertEqual(
            rules[0].ruleJSON,
            #"{"anyOf":[{"notEqual":["status",{"const":"closed"}]},{"present":"closedAt"}]}"#
        )
        XCTAssertEqual(rules[1].ruleJSON, #"{"greaterThanOrEqual":[{"divide":["price","fee"]},1]}"#)
        XCTAssertEqual(
            rules[2].ruleJSON,
            #"{"anyOf":[{"absent":"sellerId"},{"equal":["sellerId","$ownerId"]}]}"#
        )
    }

    func testPrettyRuleJSONIndentsTheSameRule() throws {
        let rule = try XCTUnwrap(DocumentPropertyConstraint.list(fromJSON: rulesJSON).first)

        let pretty = rule.prettyRuleJSON
        XCTAssertTrue(pretty.contains("\n"), pretty)
        let reparsed = try JSONSerialization.jsonObject(with: Data(pretty.utf8)) as? NSDictionary
        let original = try JSONSerialization.jsonObject(with: Data(rule.ruleJSON.utf8)) as? NSDictionary
        XCTAssertEqual(reparsed, original)
    }

    func testNoRulesDecodeToAnEmptyList() throws {
        XCTAssertEqual(try DocumentPropertyConstraint.list(fromJSON: "[]"), [])
    }

    /// A kind added by a later protocol version is kept by name rather than
    /// failing the whole list.
    func testUnknownReadKindIsKeptByName() throws {
        let rules = try DocumentPropertyConstraint.list(fromJSON: """
            [{ "name": "r", "rule": { "present": "a" }, "readsOwner": false,
               "reads": [{ "path": "a", "kind": "somethingNew" }] }]
            """)

        XCTAssertEqual(rules.first?.reads.first?.kind, .other("somethingNew"))
        XCTAssertEqual(rules.first?.reads.first?.kind.name, "somethingNew")
    }

    func testMalformedRulesAreRefused() {
        let malformed = [
            "not json",
            #"{"name": "r"}"#,
            #"[{"name": "r", "rule": {"present": "a"}, "reads": []}]"#,
            // A number is not a boolean, although NSNumber would cast it
            #"[{"name": "r", "rule": {"present": "a"}, "reads": [], "readsOwner": 1}]"#,
            #"[{"name": "r", "rule": {"present": "a"}, "reads": [{"path": "a"}], "readsOwner": false}]"#
        ]
        for json in malformed {
            XCTAssertThrowsError(try DocumentPropertyConstraint.list(fromJSON: json), json) { error in
                guard case SDKError.serializationError = error else {
                    return XCTFail("\(json): expected a serialization error, got \(error)")
                }
            }
        }
    }

    // MARK: - Violations

    func testViolationDecodes() throws {
        let violation = try XCTUnwrap(PropertyConstraintViolation.decode(fromJSON: """
            { "rule": "perUnitFee", "violation": "DivisionByZero", "message": "it divides by zero" }
            """))

        XCTAssertEqual(
            violation,
            PropertyConstraintViolation(
                rule: "perUnitFee",
                violation: .divisionByZero,
                message: "it divides by zero"
            )
        )
        XCTAssertEqual(
            violation.localizedDescription,
            "The document breaks the propertyConstraints rule \"perUnitFee\" (DivisionByZero): it divides by zero."
        )
    }

    func testEveryViolationNameRoundTrips() {
        let names = ["NotMet", "Overflow", "DivisionByZero", "NegativeExponent", "NotAnInteger"]
        let kinds: [PropertyConstraintViolation.Kind] = [
            .notMet, .overflow, .divisionByZero, .negativeExponent, .notAnInteger
        ]
        XCTAssertEqual(names.map(PropertyConstraintViolation.Kind.init(name:)), kinds)
        XCTAssertEqual(kinds.map(\.name), names)
        XCTAssertEqual(PropertyConstraintViolation.Kind(name: "Later"), .other("Later"))
    }

    func testNullMeansEveryRuleHolds() throws {
        XCTAssertNil(try PropertyConstraintViolation.decode(fromJSON: "null"))
    }

    func testMalformedViolationsAreRefused() {
        for json in ["", "[]", #"{"rule": "r", "violation": "NotMet"}"#] {
            XCTAssertThrowsError(try PropertyConstraintViolation.decode(fromJSON: json), json)
        }
    }

    // MARK: - FFI round trips

    func testWrappersRoundTripThroughTheFFI() throws {
        let sdk = try mockSDK()
        let contract = try noteContract()

        XCTAssertEqual(
            try sdk.documentPropertyConstraints(serializedContract: contract, documentType: "note"),
            []
        )
        XCTAssertNil(
            try sdk.checkDocumentPropertyConstraints(
                serializedContract: contract,
                documentType: "note",
                propertiesJSON: #"{"message":"hi"}"#,
                ownerId: ownerId
            )
        )
    }

    func testFFIErrorsKeepTheirCodes() throws {
        let sdk = try mockSDK()
        let contract = try noteContract()

        assertThrows(
            try sdk.documentPropertyConstraints(serializedContract: contract, documentType: "letter")
        ) { error in
            if case SDKError.notFound = error { return true }
            return false
        }
        assertThrows(
            try sdk.documentPropertyConstraints(serializedContract: Data([0xFF, 0x00, 0x13]), documentType: "note")
        ) { error in
            if case SDKError.serializationError = error { return true }
            return false
        }
        assertThrows(
            try sdk.documentPropertyConstraints(serializedContract: Data(), documentType: "note")
        ) { error in
            if case SDKError.invalidParameter = error { return true }
            return false
        }
        assertThrows(
            try sdk.checkDocumentPropertyConstraints(
                serializedContract: contract,
                documentType: "note",
                propertiesJSON: "[1]",
                ownerId: ownerId
            )
        ) { error in
            if case SDKError.invalidParameter = error { return true }
            return false
        }
    }

    /// The FFI reads 32 bytes behind the owner pointer, so a shorter id is
    /// refused before the call.
    func testOwnerIdMustBe32Bytes() throws {
        let sdk = try mockSDK()

        assertThrows(
            try sdk.checkDocumentPropertyConstraints(
                serializedContract: try noteContract(),
                documentType: "note",
                propertiesJSON: "{}",
                ownerId: Data(repeating: 7, count: 20)
            )
        ) { error in
            if case SDKError.invalidParameter = error { return true }
            return false
        }
    }

    // MARK: - PersistentDocumentType

    func testDocumentTypeReadsThroughItsStoredContract() throws {
        let sdk = try mockSDK()
        let stored = try persistNoteType(binarySerialization: try noteContract())
        let docType = stored.documentType

        XCTAssertFalse(docType.declaresPropertyConstraints)
        XCTAssertEqual(try docType.propertyConstraints(using: sdk), [])
        XCTAssertNil(
            try docType.propertyConstraintViolation(
                propertiesJSON: #"{"message":"hi"}"#,
                ownerId: ownerId,
                using: sdk
            )
        )
        withExtendedLifetime(stored.context) {}
    }

    func testDocumentTypeWithoutAStoredContractCannotBeRead() throws {
        let sdk = try mockSDK()
        let stored = try persistNoteType(binarySerialization: nil)

        assertThrows(try stored.documentType.propertyConstraints(using: sdk)) { error in
            if case SDKError.invalidState = error { return true }
            return false
        }
        withExtendedLifetime(stored.context) {}
    }

    func testDeclaresPropertyConstraintsReadsTheKeyword() {
        let schema: [String: Any] = [
            "type": "object",
            "propertyConstraints": ["r": ["present": "a"]]
        ]
        let docType = PersistentDocumentType(
            contractId: Data(repeating: 1, count: 32),
            name: "offer",
            schemaJSON: (try? JSONSerialization.data(withJSONObject: schema)) ?? Data(),
            propertiesJSON: Data("{}".utf8)
        )

        XCTAssertTrue(docType.declaresPropertyConstraints)
    }

    // MARK: - Helpers

    private func mockSDK() throws -> SDK {
        SDK.initialize()
        return try SDK(mockVectorsDirectory: nil)
    }

    private func noteContract() throws -> Data {
        let contract = try XCTUnwrap(Data(hexString: noteContractHex))
        // `Data(hexString:)` ignores a trailing odd digit: pin the whole fixture
        XCTAssertEqual(contract.count * 2, noteContractHex.count)
        return contract
    }

    /// A persisted document type and the context holding it, which the caller
    /// keeps alive while it reads the type's relationships.
    private struct StoredDocumentType {
        let documentType: PersistentDocumentType
        let context: ModelContext
    }

    /// Persist the `note` contract and its type the way a download does: the
    /// contract row carrying `binarySerialization`, and the parser writing the
    /// type row.
    private func persistNoteType(binarySerialization: Data?) throws -> StoredDocumentType {
        let container = try DashModelContainer.createInMemory()
        let context = ModelContext(container)
        let contractId = Data(repeating: 0xC3, count: 32)

        let contract = PersistentDataContract(
            id: contractId,
            name: "Notes",
            serializedContract: Data(),
            network: .testnet
        )
        contract.binarySerialization = binarySerialization
        context.insert(contract)
        try context.save()

        try DataContractParser.parseDataContract(
            contractData: [
                "documents": [
                    "note": [
                        "type": "object",
                        "properties": ["message": ["type": "string", "maxLength": 64, "position": 0]],
                        "additionalProperties": false
                    ]
                ]
            ],
            contractId: contractId,
            modelContext: context
        )

        let descriptor = FetchDescriptor<PersistentDocumentType>(
            predicate: #Predicate { $0.contractId == contractId }
        )
        let docType = try XCTUnwrap(try context.fetch(descriptor).first)
        return StoredDocumentType(documentType: docType, context: context)
    }

    private func assertThrows<T>(
        _ expression: @autoclosure () throws -> T,
        file: StaticString = #filePath,
        line: UInt = #line,
        matching matches: (Error) -> Bool
    ) {
        XCTAssertThrowsError(try expression(), file: file, line: line) { error in
            XCTAssertTrue(matches(error), "unexpected error: \(error)", file: file, line: line)
        }
    }
}
