export default {
  101: 'ZeroSSL API key is invalid',
  102: 'Your ZeroSSL account is not active',
  103: 'API function invalid',
  110: 'Request body was wrong. Please check your request arguments.',
  111: 'Something went wrong. If the problem persists please contact ZeroSSL support team (support@zerossl.com)',
  112: 'The target resource can not be modified',
  113: 'The syntax of the request was correct, but the request can not be processed.',
  114: 'The target resource can not be modified.',
  2800: 'Non-supported API request.',
  2801: 'You do not have the permissions to access ZeroSSL resource',
  2802: 'Certificate ID (hash) was not provided',
  2803: 'Your ZeroSSL certificate ID (hash) could not be found',
  2804: 'The current certificate cannot be issued due to unpaid invoices on your ZeroSSL account.',
  2805: 'Invalid certificate type',
  2806: 'Valid certificate type was not provided',
  2807: 'Valid certificate validity was not provided',
  2808: 'Your domain is not valid',
  2809: 'Wildcards cannot be included in multi-domain certificates',
  2810: 'User has not provided one or more invalid domains in multi-domain request',
  2811: 'User has not provided one or more duplicate domains.',
  2812: 'User has not provided any certificate domains',
  2813: 'Only issued certificates can be renewed or replaced by a new certificate.',
  2814: 'Yo do not have the permissions to access ZeroSSL certificate to renew.',
  2815: 'Only issued certificates can be renewed or replaced by a new certificate.',
  2816: 'ZeroSSL certificate to renew was not found.',
  2817: 'Limit of certificates on your ZeroSSL account was reached',
  2818: 'User has not provided a valid CSR value',
  2819: 'User has not provided a CSR value',
  2820: 'Internal error processing CSR. Please contact ZeroSSL support if this error occurs.',
  2821: 'Internal error generating certificate. Please contact ZeroSSL support if this error occurs.',
  2822: 'The requested ZeroSSL certificate could not be retrieved.',
  2823: 'ZeroSSL domain verification failed and must be retried.',
  2824: 'User has not provided a validation email for each domain in certificate',
  2825: 'User has not provided a validation email for each domain in certificate',
  2826: 'Internal error verifying domains. Please contact ZeroSSL support if this error occurs',
  2827: 'User has provided an in invalid domain verification method',
  2828: 'User has not provided a domain verification method',
  2829: 'User has provided an in invalid domain verification method or value',
  2830: 'The given certificate is not eligible for domain verification',
  2831: 'The given certificate is not ready for domain verification',
  2832: 'The given certificate has not been issued yet',
  2833: 'The given certificate cannot be cancelled due to its status',
  2834: 'Internal error cancelling certificate. Try again or contact support.',
  2837: 'Internal error resending verification email. Try again or contact support.',
  2838: 'Error retrieving domain verification status. Try again and make sure Email Verification is selected.',
  2839: 'ZeroSSL requires an upgrade from Free Plan to Basic Plan',
  2840: 'Invalid CAA records detected for some domains. Array of affected domains can be found in details object.',
  2841: 'Your ZeroSSL account has been temporarily suspended due to unpaid invoices',
  2860: 'The certificate can currently not be downloaded',
  2874: 'ZeroSSL is not able to issue certificates for this Top-Level-Domain at the moment',
  2906: 'The certificate can not be revoked currently, please try again later. If the problem persists - especially in urgent cases like key compromise - please contact our support team (support@zerossl.com).',
  2907: 'The certificate is not in a revocable state. Either the state has transitioned in the background, you are trying to revoke a certificate which can not be revoked due to its status or some process is going on in the background. If you think this is a mistake at our side please contact our support team (support@zerossl.com).',
  2908: 'Due customer protection mechanisms, your certificate can not be revoked at the moment. Try again some hours later. We temporarily disable revocation functionality, if high numbers of certificates are revoked. This was implemented as a preventive measure to limit possible loss in case of whatever related incident. Help and further information: (support@zerossl.com).',
  2909: 'The certificate can not be revoked / cancelled because it is currently being issued. If this was a mistake, you may revoke it after issuance (most probably in 1-2 minutes).',
  2910: 'The certificate has already been replaced by a new one. Does not apply for certificates where you have used the standard "renew" functionality of ZeroSSL, can only happen for special cases.',
};
