module.exports = {
  2804: 'The current certificate cannot be issued due to unpaid invoices on your ZeroSSL account.',
  2808: 'Your domain is not valid',
  2813: 'Only issued certificates can be renewed or replaced by a new certificate.',
  2814: 'Yo do not have the permissions to access ZeroSSL certificate to renew.',
  2815: 'Only issued certificates can be renewed or replaced by a new certificate.',
  2816: 'ZeroSSL certificate to renew was not found.',
  2817: 'Limit of certificates on your ZeroSSL account was reached',
  2820: 'Internal error processing CSR. Please contact ZeroSSL support if this error occurs.',
  2821: 'Internal error generating certificate. Please contact ZeroSSL support if this error occurs.',
  2839: 'ZeroSSL requires an upgrade from Free Plan to Basic Plan',
  2841: 'Your ZeroSSL account has been temporarily suspended due to unpaid invoices',
  101: 'ZeroSSL API key is invalid',
  102: 'Your ZeroSSL account is not active',
  111: 'Something went wrong. If the problem persists please contact ZeroSSL support team (support@zerossl.com)',
  2801: 'You do not have the permissions to access ZeroSSL resource',
  2803: 'Your ZeroSSL certificate ID (hash) could not be found',
  2822: 'The requested ZeroSSL certificate could not be retrieved.',
  2823: 'ZeroSSL domain verification failed and must be retried.',
  2826: 'Internal error verifying domains. Please contact ZeroSSL support if this error occurs',
  2874: 'ZeroSSL is not able to issue certificates for this Top-Level-Domain at the moment',
  2832: 'The given certificate has not been issued yet',
  2860: 'The certificate can currently not be downloaded',
};
