mod address_tests;
mod basic_tests;
mod chain_lock_update_tests;
mod comprehensive_tests;
mod core_height_increase;
mod core_update_tests;
mod data_contract_history_tests;
mod identity_and_document_tests;
mod identity_transfer_tests;
mod required_since_update_tests;
// TODO: re-enable once OperationType shielded variants are implemented
// mod shielded_tests;
mod state_sync_sentinel_tests;
pub(crate) mod state_sync_tests;
mod token_tests;
mod top_up_tests;
mod update_identities_tests;
mod upgrade_fork_tests;
mod voting_tests;
mod withdrawal_tests;
