//! Test wallet factory + `SetupGuard`.
//!
//! Each test gets a fresh-seeded `TestWallet` registered in the
//! [`super::registry::PersistentTestWalletRegistry`] **before** the
//! handle reaches the test body — that way a panic between
//! `setup` and `teardown` leaves a recoverable trail for the next
//! startup sweep.
//!
//! Wave 3a delivers the construction + accessor surface. Wave 4
//! wires `framework::setup` / `SetupGuard::teardown` against the
//! `E2eContext` accessors.

use std::collections::BTreeMap;
use std::sync::Arc;
use std::time::SystemTime;

use dpp::address_funds::{AddressFundsFeeStrategy, AddressFundsFeeStrategyStep, PlatformAddress};
use dpp::fee::Credits;
use dpp::version::PlatformVersion;
use key_wallet::account::account_collection::PlatformPaymentAccountKey;
use key_wallet::wallet::initialization::WalletAccountCreationOptions;
use key_wallet::Network;
use platform_wallet::wallet::persister::NoPlatformPersistence;
use platform_wallet::wallet::platform_addresses::InputSelection;
use platform_wallet::{
    PlatformAddressChangeSet, PlatformWallet, PlatformWalletError, PlatformWalletManager,
};
use rand::rngs::OsRng;
use rand::RngCore;

use super::harness::E2eContext;
use super::registry::{EntryStatus, PersistentTestWalletRegistry, RegistryEntry, WalletSeedHash};
use super::signer::SeedBackedPlatformAddressSigner;
use super::wait_hub::WaitEventHub;
use super::{FrameworkError, FrameworkResult};

/// DIP-17 default account/key-class used by test wallets — matches
/// the `WalletAccountCreationOptions::Default` variant which seeds
/// `PlatformPayment { account: 0, key_class: 0 }`.
pub(super) const DEFAULT_ACCOUNT_INDEX_PUB: u32 = 0;
pub(super) const DEFAULT_KEY_CLASS_PUB: u32 = 0;
const DEFAULT_ACCOUNT_INDEX: u32 = DEFAULT_ACCOUNT_INDEX_PUB;
const DEFAULT_KEY_CLASS: u32 = DEFAULT_KEY_CLASS_PUB;

/// Per-test wallet handle.
///
/// Exposes the operations test cases need (next-unused-address,
/// transfer, balances) without leaking the underlying
/// `PlatformWallet` API surface — keeps the future
/// `dash-wallet-e2e` standalone-crate refactor mechanical.
pub struct TestWallet {
    seed_bytes: [u8; 64],
    pub(crate) wallet: Arc<PlatformWallet>,
    signer: SeedBackedPlatformAddressSigner,
    /// Process-shared event hub cloned from the [`E2eContext`] at
    /// construction time. Test helpers (notably
    /// [`super::wait::wait_for_balance`]) await on the hub's `Notify`
    /// to wake on real chain / wallet events.
    wait_hub: Arc<WaitEventHub>,
}

impl std::fmt::Debug for TestWallet {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TestWallet")
            .field("wallet_id", &hex::encode(self.wallet.wallet_id()))
            .finish_non_exhaustive()
    }
}

impl TestWallet {
    /// Create a fresh-seeded test wallet, register it with the
    /// manager, and initialise its platform-address provider so
    /// `next_unused_address` / `transfer` work immediately.
    ///
    /// `seed_bytes` is generated by the caller (typically via
    /// `OsRng`) so the registry can persist it in advance and a
    /// crashed test still has a recoverable record.
    pub async fn create(
        manager: &Arc<PlatformWalletManager<NoPlatformPersistence>>,
        seed_bytes: [u8; 64],
        network: Network,
        wait_hub: Arc<WaitEventHub>,
    ) -> FrameworkResult<Self> {
        let wallet = manager
            .create_wallet_from_seed_bytes(
                network,
                seed_bytes,
                WalletAccountCreationOptions::Default,
            )
            .await
            .map_err(wallet_err)?;
        // The manager pre-builds account state but the platform
        // address provider only initializes lazily on first use; do
        // it here so test code can immediately call
        // `next_unused_address` without surprise lazy work inside the
        // test body.
        wallet.platform().initialize().await;
        let signer = SeedBackedPlatformAddressSigner::new(Arc::clone(&wallet));
        Ok(Self {
            seed_bytes,
            wallet,
            signer,
            wait_hub,
        })
    }

    /// Stable wallet id — the SHA-256 of the root xpub used as the
    /// registry key.
    pub fn id(&self) -> WalletSeedHash {
        self.wallet.wallet_id()
    }

    /// 64-byte seed bytes used to derive this wallet. Stored in the
    /// registry so the next process startup can reconstruct the
    /// wallet for a sweep.
    pub fn seed_bytes(&self) -> [u8; 64] {
        self.seed_bytes
    }

    /// Borrow the underlying `PlatformWallet`. Tests that need
    /// direct access to identity / token / core wallet APIs reach
    /// through here; the typical platform-address flow doesn't
    /// need it.
    pub fn platform_wallet(&self) -> &Arc<PlatformWallet> {
        &self.wallet
    }

    /// Borrow the seed-backed address signer used by `transfer`.
    /// Tests that broadcast transitions via the SDK directly can
    /// pass this signer in.
    pub fn address_signer(&self) -> &SeedBackedPlatformAddressSigner {
        &self.signer
    }

    /// Borrow the process-shared event hub. Used by helpers like
    /// [`super::wait::wait_for_balance`] to await on chain / wallet
    /// events instead of polling on a fixed interval.
    pub fn wait_hub(&self) -> &Arc<WaitEventHub> {
        &self.wait_hub
    }

    /// Return the next unused receive address on the wallet's
    /// default platform-payment account.
    ///
    /// Generates a new address if the gap-limit window is
    /// exhausted; balance is `0` until a sync sees an on-chain
    /// credit.
    pub async fn next_unused_address(&self) -> FrameworkResult<PlatformAddress> {
        let account_key = PlatformPaymentAccountKey {
            account: DEFAULT_ACCOUNT_INDEX,
            key_class: DEFAULT_KEY_CLASS,
        };
        self.wallet
            .platform()
            .next_unused_receive_address(account_key)
            .await
            .map_err(wallet_err)
    }

    /// Run the BLAST sync pass against the SDK to refresh balances
    /// for every tracked address.
    pub async fn sync_balances(&self) -> FrameworkResult<()> {
        self.wallet
            .platform()
            .sync_balances(None)
            .await
            .map(|_| ())
            .map_err(wallet_err)
    }

    /// Snapshot of the current cached balances.
    pub async fn balances(&self) -> BTreeMap<PlatformAddress, Credits> {
        self.wallet
            .platform()
            .addresses_with_balances()
            .await
            .into_iter()
            .collect()
    }

    /// Total credits across every tracked address.
    pub async fn total_credits(&self) -> Credits {
        self.wallet.platform().total_credits().await
    }

    /// Transfer credits to one or more outputs, paying fees from
    /// inputs. Inputs are auto-selected from the default account
    /// using the wallet's standard fee-deduction strategy.
    pub async fn transfer(
        &self,
        outputs: BTreeMap<PlatformAddress, Credits>,
    ) -> FrameworkResult<PlatformAddressChangeSet> {
        self.wallet
            .platform()
            .transfer(
                DEFAULT_ACCOUNT_INDEX,
                InputSelection::Auto,
                outputs,
                default_fee_strategy(),
                Some(PlatformVersion::latest()),
                &self.signer,
            )
            .await
            .map_err(wallet_err)
    }
}

/// Default fee strategy used by every test transfer / bank-funding
/// hop: deduct the entire fee from input #0.
pub(crate) fn default_fee_strategy() -> AddressFundsFeeStrategy {
    vec![AddressFundsFeeStrategyStep::DeductFromInput(0)]
}

/// Generate a fresh 64-byte seed and a hex string suitable for the
/// registry. Centralised so the signer + registry stay in sync if
/// the seed encoding ever needs to change.
pub fn fresh_seed() -> ([u8; 64], String) {
    let mut seed = [0u8; 64];
    OsRng.fill_bytes(&mut seed);
    let hex = hex::encode(seed);
    (seed, hex)
}

/// Build a registry entry for a freshly-seeded test wallet. The
/// caller inserts it into the registry **before** handing the
/// wallet to the test body.
pub fn registry_entry_from_seed(seed: &[u8; 64], note: Option<String>) -> RegistryEntry {
    RegistryEntry {
        seed_hex: hex::encode(seed),
        created_at: SystemTime::now(),
        status: EntryStatus::Active,
        note,
    }
}

/// Guard returned by [`super::setup`].
///
/// Tests SHOULD call [`SetupGuard::teardown`] explicitly once
/// they're done; the [`Drop`] impl is a panic-safety fallback that
/// logs a warning and relies on the next process startup running
/// `cleanup::sweep_orphans` against the persistent registry.
pub struct SetupGuard {
    /// Process-shared context. `&'static` because
    /// `E2eContext::init` returns a singleton handle.
    pub ctx: &'static E2eContext,
    /// Per-test wallet, fresh seed, registered for cleanup.
    pub test_wallet: TestWallet,
    /// `true` once [`SetupGuard::teardown`] has run successfully —
    /// flips the [`Drop`] warning off.
    pub(crate) teardown_called: bool,
}

impl SetupGuard {
    /// Sweep the test wallet's funds back to the bank and remove
    /// the entry from the persistent registry.
    ///
    /// Best-effort: a transient sync / transfer failure leaves the
    /// registry entry in place so the next process startup retries
    /// via [`super::cleanup::sweep_orphans`]. Successful teardown
    /// flips the internal flag so [`Drop`] doesn't emit a spurious
    /// warning.
    pub async fn teardown(mut self) -> FrameworkResult<()> {
        let result = super::cleanup::teardown_one(
            self.ctx.manager(),
            self.ctx.bank(),
            self.ctx.registry(),
            &self.test_wallet,
        )
        .await;
        if result.is_ok() {
            self.teardown_called = true;
        }
        result
    }
}

impl Drop for SetupGuard {
    fn drop(&mut self) {
        if !self.teardown_called {
            tracing::warn!(
                wallet_id = %hex::encode(self.test_wallet.id()),
                "SetupGuard dropped without explicit teardown — wallet will be \
                 swept on next test process startup"
            );
        }
    }
}

/// Convert a `platform_wallet::PlatformWalletError` into the
/// framework's error envelope. Kept private to this module so the
/// test surface stays free of upstream-error feature flags.
fn wallet_err(err: PlatformWalletError) -> FrameworkError {
    FrameworkError::Wallet(err.to_string())
}
