use crate::state_transition::identity_credit_transfer_transition::methods::IdentityCreditTransferTransitionMethodsV0;
use crate::state_transition::identity_credit_transfer_transition::v0::IdentityCreditTransferTransitionV0;

impl IdentityCreditTransferTransitionMethodsV0 for IdentityCreditTransferTransitionV0 {}
