pub use identity_already_exists_error::*;
pub use identity_insufficient_balance_error::*;

pub mod duplicated_identity_public_key_id_state_error;
pub mod duplicated_identity_public_key_state_error;
mod identity_already_exists_error;
mod identity_insufficient_balance_error;
pub mod identity_public_key_already_exists_for_unique_contract_bounds_error;
pub mod identity_public_key_is_disabled_error;
pub mod identity_public_key_is_read_only_error;
pub mod invalid_asset_lock_proof_value;
pub mod invalid_identity_contract_nonce_error;
pub mod invalid_identity_public_key_id_error;
pub mod invalid_identity_revision_error;
pub mod master_public_key_update_error;
pub mod max_identity_public_key_limit_reached_error;
pub mod missing_identity_public_key_ids_error;
