const emptyLocalConfigFields = [
  'CORE_MINER_MEDIANTIME',
  'CORE_MINER_ADDRESS',
  'CORE_DEVNET_NAME',
  'PLATFORM_DRIVE_TENDERDASH_GENESIS_INITIAL_PROPOSAL_CORE_CHAIN_LOCK',
  'PLATFORM_DRIVE_TENDERDASH_GENESIS_VALIDATORS_0_NAME',
  'PLATFORM_DRIVE_TENDERDASH_GENESIS_APP_HASH',
  'PLATFORM_SOURCE_PATH',
  'CORE_MASTERNODE_OPERATOR_PRIVATE_KEY'
]

const emptyTestnetConfigFields = [
  'GROUP',
  'CORE_SPORK_ADDRESS',
  'CORE_SPORK_PRIVATE_KEY',
  'CORE_MINER_MEDIANTIME',
  'CORE_MINER_ADDRESS',
  'CORE_DEVNET_NAME',
  'PLATFORM_DRIVE_TENDERDASH_GENESIS_INITIAL_PROPOSAL_CORE_CHAIN_LOCK',
  'PLATFORM_DRIVE_TENDERDASH_GENESIS_THRESHOLD_PUBLIC_KEY',
  'PLATFORM_DRIVE_TENDERDASH_GENESIS_QUORUM_HASH',
  'PLATFORM_DRIVE_TENDERDASH_GENESIS_APP_HASH',
  'PLATFORM_DPNS_SECOND_PUBLIC_KEY',
  'PLATFORM_DASHPAY_SECOND_PUBLIC_KEY',
  'PLATFORM_FEATURE_FLAGS_SECOND_PUBLIC_KEY',
  'PLATFORM_SOURCE_PATH',
  'PLATFORM_MASTERNODE_REWARD_SHARES_SECOND_PUBLIC_KEY']

module.exports = {
  EMPTY_LOCAL_CONFIG_FIELDS: emptyLocalConfigFields,
  EMPTY_TESTNET_CONFIG_FIELDS: emptyTestnetConfigFields
}
