import Foundation
import SwiftDashSDK

// Re-export SDK State Transition types for backward compatibility
public typealias StateTransition = SwiftDashSDK.StateTransition
public typealias StateTransitionType = SwiftDashSDK.StateTransitionType

// Identity transitions
public typealias IdentityCreateTransition = SwiftDashSDK.IdentityCreateTransition
public typealias IdentityUpdateTransition = SwiftDashSDK.IdentityUpdateTransition
public typealias IdentityTopUpTransition = SwiftDashSDK.IdentityTopUpTransition
public typealias IdentityCreditWithdrawalTransition = SwiftDashSDK.IdentityCreditWithdrawalTransition
public typealias IdentityCreditTransferTransition = SwiftDashSDK.IdentityCreditTransferTransition

// Data Contract transitions
public typealias DataContractCreateTransition = SwiftDashSDK.DataContractCreateTransition
public typealias DataContractUpdateTransition = SwiftDashSDK.DataContractUpdateTransition

// Document transitions
public typealias DocumentsBatchTransition = SwiftDashSDK.DocumentsBatchTransition
public typealias DocumentTransition = SwiftDashSDK.DocumentTransition
public typealias DocumentCreateTransition = SwiftDashSDK.DocumentCreateTransition
public typealias DocumentReplaceTransition = SwiftDashSDK.DocumentReplaceTransition
public typealias DocumentDeleteTransition = SwiftDashSDK.DocumentDeleteTransition
public typealias DocumentTransferTransition = SwiftDashSDK.DocumentTransferTransition
public typealias DocumentPurchaseTransition = SwiftDashSDK.DocumentPurchaseTransition
public typealias DocumentUpdatePriceTransition = SwiftDashSDK.DocumentUpdatePriceTransition

// Token transitions
public typealias TokenTransferTransition = SwiftDashSDK.TokenTransferTransition
public typealias TokenMintTransition = SwiftDashSDK.TokenMintTransition
public typealias TokenBurnTransition = SwiftDashSDK.TokenBurnTransition
public typealias TokenFreezeTransition = SwiftDashSDK.TokenFreezeTransition
public typealias TokenUnfreezeTransition = SwiftDashSDK.TokenUnfreezeTransition

// Supporting types
public typealias Pooling = SwiftDashSDK.Pooling
public typealias StateTransitionResult = SwiftDashSDK.StateTransitionResult
public typealias StateTransitionError = SwiftDashSDK.StateTransitionError
public typealias BroadcastStateTransitionRequest = SwiftDashSDK.BroadcastStateTransitionRequest
public typealias WaitForStateTransitionResultRequest = SwiftDashSDK.WaitForStateTransitionResultRequest
