#!/usr/bin/env bash

FULL_PATH=$(realpath "$0")
DIR_PATH=$(dirname "$FULL_PATH")
ROOT_PATH=$(dirname "$DIR_PATH")

# Check if packages/dashmate/dist/index.js exists
if [ ! -f "$ROOT_PATH/packages/dashmate/dist/index.js" ]; then
  echo "Error: dashmate is not built. Please run 'yarn build'."
  exit 1
fi

node -r $ROOT_PATH/.pnp.cjs --loader=$ROOT_PATH/.pnp.loader.mjs $ROOT_PATH/packages/dashmate/bin/run.js "$@"
