package org.dashfoundation.dashsdk

import androidx.test.ext.junit.runners.AndroidJUnit4
import org.dashfoundation.dashsdk.ffi.DashSDKException
import org.dashfoundation.dashsdk.ffi.NativeLoader
import org.dashfoundation.dashsdk.ffi.QueriesNative
import org.dashfoundation.dashsdk.ffi.SdkNative
import org.dashfoundation.dashsdk.queries.DocumentPropertyConstraint
import org.dashfoundation.dashsdk.queries.PropertyConstraintViolation
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Round trips of the two `propertyConstraints` JNI exports through
 * `rs-sdk-ffi` on a device: the marshalling of the contract bytes, the
 * strings and the owner id, and the error codes the Kotlin side maps
 * (`DashSdkError.fromNative`). Rust's own tests cover the rules; the fixture
 * declares none, so the answers are `[]` and `null` at any protocol version.
 * No network access: `createTrusted` only builds the client. Kotlin
 * counterpart of the FFI round trips in the Swift SDK's
 * `DocumentPropertyConstraintsTests`.
 */
@RunWith(AndroidJUnit4::class)
class PropertyConstraintsFfiTest {

    /**
     * The platform serialization of a contract created at protocol version
     * 13, owned by `[7; 32]`, declaring one `note` type with a string
     * `message` and no rules (the Swift test's fixture, generated by
     * rs-sdk-ffi's `serialize_to_bytes_with_platform_version`).
     */
    private val noteContract = (
        "013ac40651a4bcb91c3f5c1e458a1c95e48dc2c8259003dd580cab11a5f02ed4850100000000010100000101070707070707" +
            "07070707070707070707070707070707070707070707070707070001046e6f7465160312047479706512066f626a65637412" +
            "0a70726f70657274696573160112076d65737361676516031204747970651206737472696e6712096d61784c656e67746805" +
            "801208706f736974696f6e050012146164646974696f6e616c50726f70657274696573130000000000000000000000"
        ).chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private val ownerId = ByteArray(32) { 7 }

    private var handle = 0L

    @Before
    fun createSdk() {
        NativeLoader.ensureLoaded()
        handle = SdkNative.createTrusted(
            network = 1,
            dapiAddresses = null,
            quorumUrl = null,
            skipAssetLockProofVerification = false,
            requestRetryCount = 3,
            requestTimeoutMs = 30_000,
            platformVersion = 0,
        )
        assertNotEquals("createTrusted must return a live handle", 0L, handle)
    }

    @After
    fun destroySdk() {
        SdkNative.destroy(handle)
    }

    @Test
    fun shouldReadNoRulesAndNoViolationForATypeDeclaringNone() {
        val rules = QueriesNative.dataContractGetPropertyConstraints(handle, noteContract, "note")
        assertEquals(emptyList<DocumentPropertyConstraint>(), DocumentPropertyConstraint.listFromJson(rules!!))

        val verdict = QueriesNative.dataContractCheckPropertyConstraints(
            handle,
            noteContract,
            "note",
            """{"message":"hi"}""",
            ownerId,
        )
        assertEquals("null", verdict)
        assertNull(PropertyConstraintViolation.fromJson(verdict!!))
    }

    @Test
    fun shouldKeepTheNativeErrorCodes() {
        // DashSDKErrorCode: 1 InvalidParameter, 4 SerializationError, 7 NotFound
        assertCode(7) { QueriesNative.dataContractGetPropertyConstraints(handle, noteContract, "letter") }
        assertCode(4) {
            QueriesNative.dataContractGetPropertyConstraints(handle, byteArrayOf(-1, 0, 19), "note")
        }
        assertCode(1) { QueriesNative.dataContractGetPropertyConstraints(handle, ByteArray(0), "note") }
        assertCode(1) {
            QueriesNative.dataContractCheckPropertyConstraints(handle, noteContract, "note", "[1]", ownerId)
        }
    }

    /** The C function reads 32 bytes behind the owner pointer, so the JNI refuses a shorter id. */
    @Test
    fun shouldRefuseAnOwnerIdThatIsNot32Bytes() {
        assertCode(1) {
            QueriesNative.dataContractCheckPropertyConstraints(
                handle,
                noteContract,
                "note",
                "{}",
                ByteArray(20) { 7 },
            )
        }
    }

    private fun assertCode(code: Int, call: () -> Unit) {
        val error = assertThrows(DashSDKException::class.java) { call() }
        assertEquals(error.message, code, error.code)
    }
}
