wallet-utils-contract: &wallet-utils-contract
  - .github/workflows/tests*
  - packages/wallet-utils-contract/src/**
  - packages/wallet-utils-contract/schema/**
  - packages/wallet-utils-contract/Cargo.toml

token-history-contract: &token-history-contract
  - .github/workflows/tests*
  - packages/token-history-contract/src/**
  - packages/token-history-contract/schema/**
  - packages/token-history-contract/Cargo.toml

document-history-contract: &document-history-contract
  - .github/workflows/tests*
  - packages/document-history-contract/src/**
  - packages/document-history-contract/schema/**
  - packages/document-history-contract/Cargo.toml

keyword-search-contract: &keyword-search-contract
  - .github/workflows/tests*
  - packages/keyword-search-contract/src/**
  - packages/keyword-search-contract/schema/**
  - packages/keyword-search-contract/Cargo.toml

dashpay-contract: &dashpay-contract
  - .github/workflows/tests*
  - packages/dashpay-contract/src/**
  - packages/dashpay-contract/schema/**
  - packages/dashpay-contract/Cargo.toml

masternode-reward-shares-contract: &masternode-reward-shares-contract
  - .github/workflows/tests*
  - packages/masternode-reward-shares-contract/src/**
  - packages/masternode-reward-shares-contract/schema/**
  - packages/masternode-reward-shares-contract/Cargo.toml

withdrawals-contract: &withdrawals-contract
  - .github/workflows/tests*
  - packages/withdrawals-contract/src/**
  - packages/withdrawals-contract/schema/**
  - packages/withdrawals-contract/Cargo.toml

dpns-contract: &dpns-contract
  - .github/workflows/tests*
  - packages/dpns-contract/src/**
  - packages/dpns-contract/schema/**
  - packages/dpns-contract/Cargo.toml

json-schema-compatibility-validator: &json-schema-compatibility-validator
  - .github/workflows/tests*
  - packages/rs-json-schema-compatibility-validator/**

data-contracts: &data-contracts
  - .github/workflows/tests*
  - packages/data-contracts/**
  - *dashpay-contract
  - *masternode-reward-shares-contract
  - *dpns-contract
  - *withdrawals-contract
  - *wallet-utils-contract
  - *token-history-contract
  - *keyword-search-contract
  - *document-history-contract

dpp: &dpp
  - .github/workflows/tests*
  - packages/rs-dpp/**
  - packages/rs-dpp-json-convertible-derive/**
  - *data-contracts
  - *json-schema-compatibility-validator
  - packages/rs-platform-serialization/**
  - packages/rs-platform-serialization-derive/**
  - packages/rs-platform-value/**
  - packages/rs-platform-value-convertible/**
  - packages/rs-platform-version/**
  - packages/rs-platform-versioning/**

wasm-dpp:
  - .github/workflows/tests*
  - packages/wasm-dpp/src/**
  - packages/wasm-dpp/Cargo.toml
  - *dpp

wasm-dpp2:
  - .github/workflows/tests*
  - packages/wasm-dpp2/src/**
  - packages/wasm-dpp2/Cargo.toml
  - *dpp

drive: &drive
  - .github/workflows/tests*
  - packages/rs-drive/**
  - *dpp

simple-signer: &simple-signer
  - .github/workflows/tests*
  - packages/simple-signer/**

strategy-tests: &strategy-tests
  - .github/workflows/tests*
  - packages/strategy-tests/**
  - *simple-signer
  - *drive

platform-query-wire: &platform_query_wire
  - .github/workflows/tests*
  - packages/rs-platform-query-wire/**
  - *drive

drive-abci:
  - .github/workflows/tests*
  - packages/rs-drive-abci/**
  - *drive
  - *simple-signer
  - *strategy-tests
  - *platform_query_wire

dash-async: &dash_async
  - .github/workflows/tests*
  - packages/rs-dash-async/**

dash-context-provider: &context_provider
  - .github/workflows/tests*
  - packages/rs-context-provider/**
  - *dash_async
  - *drive

rs-sdk-trusted-context-provider: &sdk_trusted_context_provider
  - .github/workflows/tests*
  - packages/rs-sdk-trusted-context-provider/**
  - *dash_async
  - *context_provider
  - *dpp

dapi-grpc: &dapi_grpc
  - .github/workflows/tests*
  - packages/rs-platform-version/**
  - packages/rs-dash-platform-macros/**
  - packages/dapi-grpc/src/**
  - packages/dapi-grpc/protos/**
  - packages/dapi-grpc/build.rs
  - packages/dapi-grpc/Cargo.toml

rs-dapi-client: &dapi_client
  - .github/workflows/tests*
  - packages/rs-dapi-client/**
  - *dapi_grpc

rs-dapi:
  - .github/workflows/tests*
  - packages/rs-dapi/**
  - *dapi_grpc
  - *dpp
  - packages/rs-dash-event-bus/**

platform-encryption: &platform_encryption
  - .github/workflows/tests*
  - packages/rs-platform-encryption/**

dash-platform-queries: &platform_queries
  - .github/workflows/tests*
  - packages/dash-platform-queries/**

dash-sdk: &sdk
  - .github/workflows/tests*
  - packages/rs-drive-proof-verifier/**
  - packages/rs-sdk/**
  - *platform_queries
  - *dash_async
  - *context_provider
  - *sdk_trusted_context_provider
  - *platform_encryption
  - *dapi_client
  - *drive

rs-sdk-ffi: &sdk_ffi
  - .github/workflows/tests*
  - packages/rs-sdk-ffi/**
  - *simple-signer
  - *dash_async
  - *sdk

wasm-sdk:
  - .github/workflows/tests*
  - packages/wasm-sdk/src/**
  - packages/wasm-sdk/Cargo.toml
  - *sdk

platform-wallet: &platform_wallet
  - .github/workflows/tests*
  - packages/rs-platform-wallet/**
  - *platform_encryption
  - *sdk

platform-wallet-storage:
  - .github/workflows/tests*
  - packages/rs-platform-wallet-storage/**
  - *platform_wallet

platform-wallet-ffi: &platform_wallet_ffi
  - .github/workflows/tests*
  - packages/rs-platform-wallet-ffi/**
  - *platform_wallet
  - *sdk_ffi

rs-unified-sdk-ffi:
  - .github/workflows/tests*
  - packages/rs-unified-sdk-ffi/**
  - *platform_wallet_ffi
  - *sdk_ffi

rs-unified-sdk-jni:
  - .github/workflows/tests*
  - packages/rs-unified-sdk-jni/**
  - *platform_wallet_ffi
  - *sdk_ffi

wasm-drive-verify:
  - .github/workflows/tests*
  - packages/wasm-drive-verify/**
  - *drive

check-features:
  - .github/workflows/tests*
  - packages/check-features/**

dash-platform-balance-checker:
  - .github/workflows/tests*
  - packages/dash-platform-balance-checker/**
  - *sdk

rs-scripts:
  - .github/workflows/tests*
  - packages/rs-scripts/**
  - *data-contracts
