mod identity_does_not_have_enough_token_balance_error;
mod identity_token_account_already_frozen_error;
mod identity_token_account_frozen_error;
mod identity_token_account_not_frozen_error;
mod invalid_group_position_error;
mod invalid_token_claim_property_mismatch;
mod new_authorized_action_taker_group_does_not_exist_error;
mod new_authorized_action_taker_identity_does_not_exist_error;
mod new_authorized_action_taker_main_group_not_set_error;
mod new_tokens_destination_identity_does_not_exist_error;
mod token_already_paused_error;
mod token_is_paused_error;
mod token_mint_past_max_supply_error;
mod token_not_paused_error;
mod token_setting_max_supply_to_less_than_current_supply_error;
mod unauthorized_token_action_error;
mod invalid_token_claim_no_current_rewards;
mod invalid_token_claim_wrong_claimant;

pub use identity_does_not_have_enough_token_balance_error::*;
pub use identity_token_account_already_frozen_error::*;
pub use identity_token_account_frozen_error::*;
pub use identity_token_account_not_frozen_error::*;
pub use invalid_group_position_error::*;
pub use invalid_token_claim_property_mismatch::*;
pub use new_authorized_action_taker_group_does_not_exist_error::*;
pub use new_authorized_action_taker_identity_does_not_exist_error::*;
pub use new_authorized_action_taker_main_group_not_set_error::*;
pub use new_tokens_destination_identity_does_not_exist_error::*;
pub use token_already_paused_error::*;
pub use token_is_paused_error::*;
pub use token_mint_past_max_supply_error::*;
pub use token_not_paused_error::*;
pub use token_setting_max_supply_to_less_than_current_supply_error::*;
pub use unauthorized_token_action_error::*;
pub use invalid_token_claim_no_current_rewards::*;
pub use invalid_token_claim_wrong_claimant::*;
