// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Core.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdirect-ivar-access"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(BlockHeaders);
GPBObjCClassDeclaration(BloomFilter);
GPBObjCClassDeclaration(GetBlockchainStatusResponse);
GPBObjCClassDeclaration(GetBlockchainStatusResponse_Chain);
GPBObjCClassDeclaration(GetBlockchainStatusResponse_Network);
GPBObjCClassDeclaration(GetBlockchainStatusResponse_NetworkFee);
GPBObjCClassDeclaration(GetBlockchainStatusResponse_Time);
GPBObjCClassDeclaration(GetBlockchainStatusResponse_Version);
GPBObjCClassDeclaration(InstantSendLockMessages);
GPBObjCClassDeclaration(RawTransactions);

#pragma mark - CoreRoot

@implementation CoreRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - CoreRoot_FileDescriptor

static GPBFileDescriptor *CoreRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"org.dash.platform.dapi.v0"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetBlockchainStatusRequest

@implementation GetBlockchainStatusRequest


typedef struct GetBlockchainStatusRequest__storage_ {
  uint32_t _has_storage_[1];
} GetBlockchainStatusRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockchainStatusRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(GetBlockchainStatusRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetBlockchainStatusResponse

@implementation GetBlockchainStatusResponse

@dynamic hasVersion, version;
@dynamic hasTime, time;
@dynamic status;
@dynamic syncProgress;
@dynamic hasChain, chain;
@dynamic hasNetwork, network;

typedef struct GetBlockchainStatusResponse__storage_ {
  uint32_t _has_storage_[1];
  GetBlockchainStatusResponse_Status status;
  GetBlockchainStatusResponse_Version *version;
  GetBlockchainStatusResponse_Time *time;
  GetBlockchainStatusResponse_Chain *chain;
  GetBlockchainStatusResponse_Network *network;
  double syncProgress;
} GetBlockchainStatusResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "version",
        .dataTypeSpecific.clazz = GPBObjCClass(GetBlockchainStatusResponse_Version),
        .number = GetBlockchainStatusResponse_FieldNumber_Version,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "time",
        .dataTypeSpecific.clazz = GPBObjCClass(GetBlockchainStatusResponse_Time),
        .number = GetBlockchainStatusResponse_FieldNumber_Time,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse__storage_, time),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = GetBlockchainStatusResponse_Status_EnumDescriptor,
        .number = GetBlockchainStatusResponse_FieldNumber_Status,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "syncProgress",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_FieldNumber_SyncProgress,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse__storage_, syncProgress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "chain",
        .dataTypeSpecific.clazz = GPBObjCClass(GetBlockchainStatusResponse_Chain),
        .number = GetBlockchainStatusResponse_FieldNumber_Chain,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse__storage_, chain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "network",
        .dataTypeSpecific.clazz = GPBObjCClass(GetBlockchainStatusResponse_Network),
        .number = GetBlockchainStatusResponse_FieldNumber_Network,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse__storage_, network),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockchainStatusResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockchainStatusResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GetBlockchainStatusResponse_Status_RawValue(GetBlockchainStatusResponse *message) {
  GPBDescriptor *descriptor = [GetBlockchainStatusResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetBlockchainStatusResponse_FieldNumber_Status];
  return GPBGetMessageRawEnumField(message, field);
}

void SetGetBlockchainStatusResponse_Status_RawValue(GetBlockchainStatusResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [GetBlockchainStatusResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetBlockchainStatusResponse_FieldNumber_Status];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - Enum GetBlockchainStatusResponse_Status

GPBEnumDescriptor *GetBlockchainStatusResponse_Status_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "NotStarted\000Syncing\000Ready\000Error\000";
    static const int32_t values[] = {
        GetBlockchainStatusResponse_Status_NotStarted,
        GetBlockchainStatusResponse_Status_Syncing,
        GetBlockchainStatusResponse_Status_Ready,
        GetBlockchainStatusResponse_Status_Error,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetBlockchainStatusResponse_Status)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetBlockchainStatusResponse_Status_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetBlockchainStatusResponse_Status_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetBlockchainStatusResponse_Status_NotStarted:
    case GetBlockchainStatusResponse_Status_Syncing:
    case GetBlockchainStatusResponse_Status_Ready:
    case GetBlockchainStatusResponse_Status_Error:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - GetBlockchainStatusResponse_Version

@implementation GetBlockchainStatusResponse_Version

@dynamic protocol;
@dynamic software;
@dynamic agent;

typedef struct GetBlockchainStatusResponse_Version__storage_ {
  uint32_t _has_storage_[1];
  uint32_t protocol;
  uint32_t software;
  NSString *agent;
} GetBlockchainStatusResponse_Version__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "protocol",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Version_FieldNumber_Protocol,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Version__storage_, protocol),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "software",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Version_FieldNumber_Software,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Version__storage_, software),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "agent",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Version_FieldNumber_Agent,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Version__storage_, agent),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockchainStatusResponse_Version class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockchainStatusResponse_Version__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    [localDescriptor setupContainingMessageClass:GPBObjCClass(GetBlockchainStatusResponse)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetBlockchainStatusResponse_Time

@implementation GetBlockchainStatusResponse_Time

@dynamic now;
@dynamic offset;
@dynamic median;

typedef struct GetBlockchainStatusResponse_Time__storage_ {
  uint32_t _has_storage_[1];
  uint32_t now;
  int32_t offset;
  uint32_t median;
} GetBlockchainStatusResponse_Time__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "now",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Time_FieldNumber_Now,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Time__storage_, now),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "offset",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Time_FieldNumber_Offset,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Time__storage_, offset),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "median",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Time_FieldNumber_Median,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Time__storage_, median),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockchainStatusResponse_Time class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockchainStatusResponse_Time__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    [localDescriptor setupContainingMessageClass:GPBObjCClass(GetBlockchainStatusResponse)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetBlockchainStatusResponse_Chain

@implementation GetBlockchainStatusResponse_Chain

@dynamic name;
@dynamic headersCount;
@dynamic blocksCount;
@dynamic bestBlockHash;
@dynamic difficulty;
@dynamic chainWork;
@dynamic isSynced;
@dynamic syncProgress;

typedef struct GetBlockchainStatusResponse_Chain__storage_ {
  uint32_t _has_storage_[1];
  uint32_t headersCount;
  uint32_t blocksCount;
  NSString *name;
  NSData *bestBlockHash;
  NSData *chainWork;
  double difficulty;
  double syncProgress;
} GetBlockchainStatusResponse_Chain__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Chain__storage_, name),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "headersCount",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_HeadersCount,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Chain__storage_, headersCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "blocksCount",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_BlocksCount,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Chain__storage_, blocksCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "bestBlockHash",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_BestBlockHash,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Chain__storage_, bestBlockHash),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "difficulty",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_Difficulty,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Chain__storage_, difficulty),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "chainWork",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_ChainWork,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Chain__storage_, chainWork),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "isSynced",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_IsSynced,
        .hasIndex = 6,
        .offset = 7,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "syncProgress",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Chain_FieldNumber_SyncProgress,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Chain__storage_, syncProgress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockchainStatusResponse_Chain class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockchainStatusResponse_Chain__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    [localDescriptor setupContainingMessageClass:GPBObjCClass(GetBlockchainStatusResponse)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetBlockchainStatusResponse_NetworkFee

@implementation GetBlockchainStatusResponse_NetworkFee

@dynamic relay;
@dynamic incremental;

typedef struct GetBlockchainStatusResponse_NetworkFee__storage_ {
  uint32_t _has_storage_[1];
  double relay;
  double incremental;
} GetBlockchainStatusResponse_NetworkFee__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "relay",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_NetworkFee_FieldNumber_Relay,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_NetworkFee__storage_, relay),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "incremental",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_NetworkFee_FieldNumber_Incremental,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_NetworkFee__storage_, incremental),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockchainStatusResponse_NetworkFee class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockchainStatusResponse_NetworkFee__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    [localDescriptor setupContainingMessageClass:GPBObjCClass(GetBlockchainStatusResponse)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetBlockchainStatusResponse_Network

@implementation GetBlockchainStatusResponse_Network

@dynamic peersCount;
@dynamic hasFee, fee;

typedef struct GetBlockchainStatusResponse_Network__storage_ {
  uint32_t _has_storage_[1];
  uint32_t peersCount;
  GetBlockchainStatusResponse_NetworkFee *fee;
} GetBlockchainStatusResponse_Network__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "peersCount",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockchainStatusResponse_Network_FieldNumber_PeersCount,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Network__storage_, peersCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "fee",
        .dataTypeSpecific.clazz = GPBObjCClass(GetBlockchainStatusResponse_NetworkFee),
        .number = GetBlockchainStatusResponse_Network_FieldNumber_Fee,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetBlockchainStatusResponse_Network__storage_, fee),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockchainStatusResponse_Network class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockchainStatusResponse_Network__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    [localDescriptor setupContainingMessageClass:GPBObjCClass(GetBlockchainStatusResponse)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetMasternodeStatusRequest

@implementation GetMasternodeStatusRequest


typedef struct GetMasternodeStatusRequest__storage_ {
  uint32_t _has_storage_[1];
} GetMasternodeStatusRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetMasternodeStatusRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(GetMasternodeStatusRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetMasternodeStatusResponse

@implementation GetMasternodeStatusResponse

@dynamic status;
@dynamic proTxHash;
@dynamic posePenalty;
@dynamic isSynced;
@dynamic syncProgress;

typedef struct GetMasternodeStatusResponse__storage_ {
  uint32_t _has_storage_[1];
  GetMasternodeStatusResponse_Status status;
  uint32_t posePenalty;
  NSData *proTxHash;
  double syncProgress;
} GetMasternodeStatusResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = GetMasternodeStatusResponse_Status_EnumDescriptor,
        .number = GetMasternodeStatusResponse_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetMasternodeStatusResponse__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "proTxHash",
        .dataTypeSpecific.clazz = Nil,
        .number = GetMasternodeStatusResponse_FieldNumber_ProTxHash,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetMasternodeStatusResponse__storage_, proTxHash),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "posePenalty",
        .dataTypeSpecific.clazz = Nil,
        .number = GetMasternodeStatusResponse_FieldNumber_PosePenalty,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetMasternodeStatusResponse__storage_, posePenalty),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "isSynced",
        .dataTypeSpecific.clazz = Nil,
        .number = GetMasternodeStatusResponse_FieldNumber_IsSynced,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "syncProgress",
        .dataTypeSpecific.clazz = Nil,
        .number = GetMasternodeStatusResponse_FieldNumber_SyncProgress,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GetMasternodeStatusResponse__storage_, syncProgress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetMasternodeStatusResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetMasternodeStatusResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GetMasternodeStatusResponse_Status_RawValue(GetMasternodeStatusResponse *message) {
  GPBDescriptor *descriptor = [GetMasternodeStatusResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetMasternodeStatusResponse_FieldNumber_Status];
  return GPBGetMessageRawEnumField(message, field);
}

void SetGetMasternodeStatusResponse_Status_RawValue(GetMasternodeStatusResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [GetMasternodeStatusResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetMasternodeStatusResponse_FieldNumber_Status];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - Enum GetMasternodeStatusResponse_Status

GPBEnumDescriptor *GetMasternodeStatusResponse_Status_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000WaitingForProtx\000PoseBanned\000Remov"
        "ed\000OperatorKeyChanged\000ProtxIpChanged\000Rea"
        "dy\000Error\000";
    static const int32_t values[] = {
        GetMasternodeStatusResponse_Status_Unknown,
        GetMasternodeStatusResponse_Status_WaitingForProtx,
        GetMasternodeStatusResponse_Status_PoseBanned,
        GetMasternodeStatusResponse_Status_Removed,
        GetMasternodeStatusResponse_Status_OperatorKeyChanged,
        GetMasternodeStatusResponse_Status_ProtxIpChanged,
        GetMasternodeStatusResponse_Status_Ready,
        GetMasternodeStatusResponse_Status_Error,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(GetMasternodeStatusResponse_Status)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:GetMasternodeStatusResponse_Status_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL GetMasternodeStatusResponse_Status_IsValidValue(int32_t value__) {
  switch (value__) {
    case GetMasternodeStatusResponse_Status_Unknown:
    case GetMasternodeStatusResponse_Status_WaitingForProtx:
    case GetMasternodeStatusResponse_Status_PoseBanned:
    case GetMasternodeStatusResponse_Status_Removed:
    case GetMasternodeStatusResponse_Status_OperatorKeyChanged:
    case GetMasternodeStatusResponse_Status_ProtxIpChanged:
    case GetMasternodeStatusResponse_Status_Ready:
    case GetMasternodeStatusResponse_Status_Error:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - GetBlockRequest

@implementation GetBlockRequest

@dynamic blockOneOfCase;
@dynamic height;
@dynamic hash_p;

typedef struct GetBlockRequest__storage_ {
  uint32_t _has_storage_[2];
  uint32_t height;
  NSString *hash_p;
} GetBlockRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "height",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockRequest_FieldNumber_Height,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(GetBlockRequest__storage_, height),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "hash_p",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockRequest_FieldNumber_Hash_p,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(GetBlockRequest__storage_, hash_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    static const char *oneofs[] = {
      "block",
    };
    [localDescriptor setupOneofs:oneofs
                           count:(uint32_t)(sizeof(oneofs) / sizeof(char*))
                   firstHasIndex:-1];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void GetBlockRequest_ClearBlockOneOfCase(GetBlockRequest *message) {
  GPBDescriptor *descriptor = [GetBlockRequest descriptor];
  GPBOneofDescriptor *oneof = [descriptor.oneofs objectAtIndex:0];
  GPBClearOneof(message, oneof);
}
#pragma mark - GetBlockResponse

@implementation GetBlockResponse

@dynamic block;

typedef struct GetBlockResponse__storage_ {
  uint32_t _has_storage_[1];
  NSData *block;
} GetBlockResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "block",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBlockResponse_FieldNumber_Block,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBlockResponse__storage_, block),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBlockResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBlockResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetBestBlockHeightRequest

@implementation GetBestBlockHeightRequest


typedef struct GetBestBlockHeightRequest__storage_ {
  uint32_t _has_storage_[1];
} GetBestBlockHeightRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBestBlockHeightRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(GetBestBlockHeightRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetBestBlockHeightResponse

@implementation GetBestBlockHeightResponse

@dynamic height;

typedef struct GetBestBlockHeightResponse__storage_ {
  uint32_t _has_storage_[1];
  uint32_t height;
} GetBestBlockHeightResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "height",
        .dataTypeSpecific.clazz = Nil,
        .number = GetBestBlockHeightResponse_FieldNumber_Height,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetBestBlockHeightResponse__storage_, height),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetBestBlockHeightResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetBestBlockHeightResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BroadcastTransactionRequest

@implementation BroadcastTransactionRequest

@dynamic transaction;
@dynamic allowHighFees;
@dynamic bypassLimits;

typedef struct BroadcastTransactionRequest__storage_ {
  uint32_t _has_storage_[1];
  NSData *transaction;
} BroadcastTransactionRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "transaction",
        .dataTypeSpecific.clazz = Nil,
        .number = BroadcastTransactionRequest_FieldNumber_Transaction,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BroadcastTransactionRequest__storage_, transaction),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "allowHighFees",
        .dataTypeSpecific.clazz = Nil,
        .number = BroadcastTransactionRequest_FieldNumber_AllowHighFees,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "bypassLimits",
        .dataTypeSpecific.clazz = Nil,
        .number = BroadcastTransactionRequest_FieldNumber_BypassLimits,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BroadcastTransactionRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BroadcastTransactionRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BroadcastTransactionResponse

@implementation BroadcastTransactionResponse

@dynamic transactionId;

typedef struct BroadcastTransactionResponse__storage_ {
  uint32_t _has_storage_[1];
  NSString *transactionId;
} BroadcastTransactionResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "transactionId",
        .dataTypeSpecific.clazz = Nil,
        .number = BroadcastTransactionResponse_FieldNumber_TransactionId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BroadcastTransactionResponse__storage_, transactionId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BroadcastTransactionResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BroadcastTransactionResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetTransactionRequest

@implementation GetTransactionRequest

@dynamic id_p;

typedef struct GetTransactionRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *id_p;
} GetTransactionRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.clazz = Nil,
        .number = GetTransactionRequest_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetTransactionRequest__storage_, id_p),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetTransactionRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetTransactionRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetTransactionResponse

@implementation GetTransactionResponse

@dynamic transaction;
@dynamic blockHash;
@dynamic height;
@dynamic confirmations;
@dynamic isInstantLocked;
@dynamic isChainLocked;

typedef struct GetTransactionResponse__storage_ {
  uint32_t _has_storage_[1];
  uint32_t height;
  uint32_t confirmations;
  NSData *transaction;
  NSData *blockHash;
} GetTransactionResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "transaction",
        .dataTypeSpecific.clazz = Nil,
        .number = GetTransactionResponse_FieldNumber_Transaction,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetTransactionResponse__storage_, transaction),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "blockHash",
        .dataTypeSpecific.clazz = Nil,
        .number = GetTransactionResponse_FieldNumber_BlockHash,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetTransactionResponse__storage_, blockHash),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "height",
        .dataTypeSpecific.clazz = Nil,
        .number = GetTransactionResponse_FieldNumber_Height,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetTransactionResponse__storage_, height),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "confirmations",
        .dataTypeSpecific.clazz = Nil,
        .number = GetTransactionResponse_FieldNumber_Confirmations,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GetTransactionResponse__storage_, confirmations),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "isInstantLocked",
        .dataTypeSpecific.clazz = Nil,
        .number = GetTransactionResponse_FieldNumber_IsInstantLocked,
        .hasIndex = 4,
        .offset = 5,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "isChainLocked",
        .dataTypeSpecific.clazz = Nil,
        .number = GetTransactionResponse_FieldNumber_IsChainLocked,
        .hasIndex = 6,
        .offset = 7,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetTransactionResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetTransactionResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - BlockHeadersWithChainLocksRequest

@implementation BlockHeadersWithChainLocksRequest

@dynamic fromBlockOneOfCase;
@dynamic fromBlockHash;
@dynamic fromBlockHeight;
@dynamic count;

typedef struct BlockHeadersWithChainLocksRequest__storage_ {
  uint32_t _has_storage_[2];
  uint32_t fromBlockHeight;
  uint32_t count;
  NSData *fromBlockHash;
} BlockHeadersWithChainLocksRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fromBlockHash",
        .dataTypeSpecific.clazz = Nil,
        .number = BlockHeadersWithChainLocksRequest_FieldNumber_FromBlockHash,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(BlockHeadersWithChainLocksRequest__storage_, fromBlockHash),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "fromBlockHeight",
        .dataTypeSpecific.clazz = Nil,
        .number = BlockHeadersWithChainLocksRequest_FieldNumber_FromBlockHeight,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(BlockHeadersWithChainLocksRequest__storage_, fromBlockHeight),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "count",
        .dataTypeSpecific.clazz = Nil,
        .number = BlockHeadersWithChainLocksRequest_FieldNumber_Count,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BlockHeadersWithChainLocksRequest__storage_, count),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BlockHeadersWithChainLocksRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BlockHeadersWithChainLocksRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    static const char *oneofs[] = {
      "fromBlock",
    };
    [localDescriptor setupOneofs:oneofs
                           count:(uint32_t)(sizeof(oneofs) / sizeof(char*))
                   firstHasIndex:-1];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void BlockHeadersWithChainLocksRequest_ClearFromBlockOneOfCase(BlockHeadersWithChainLocksRequest *message) {
  GPBDescriptor *descriptor = [BlockHeadersWithChainLocksRequest descriptor];
  GPBOneofDescriptor *oneof = [descriptor.oneofs objectAtIndex:0];
  GPBClearOneof(message, oneof);
}
#pragma mark - BlockHeadersWithChainLocksResponse

@implementation BlockHeadersWithChainLocksResponse

@dynamic responsesOneOfCase;
@dynamic blockHeaders;
@dynamic chainLock;

typedef struct BlockHeadersWithChainLocksResponse__storage_ {
  uint32_t _has_storage_[2];
  BlockHeaders *blockHeaders;
  NSData *chainLock;
} BlockHeadersWithChainLocksResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "blockHeaders",
        .dataTypeSpecific.clazz = GPBObjCClass(BlockHeaders),
        .number = BlockHeadersWithChainLocksResponse_FieldNumber_BlockHeaders,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(BlockHeadersWithChainLocksResponse__storage_, blockHeaders),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "chainLock",
        .dataTypeSpecific.clazz = Nil,
        .number = BlockHeadersWithChainLocksResponse_FieldNumber_ChainLock,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(BlockHeadersWithChainLocksResponse__storage_, chainLock),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BlockHeadersWithChainLocksResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BlockHeadersWithChainLocksResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    static const char *oneofs[] = {
      "responses",
    };
    [localDescriptor setupOneofs:oneofs
                           count:(uint32_t)(sizeof(oneofs) / sizeof(char*))
                   firstHasIndex:-1];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void BlockHeadersWithChainLocksResponse_ClearResponsesOneOfCase(BlockHeadersWithChainLocksResponse *message) {
  GPBDescriptor *descriptor = [BlockHeadersWithChainLocksResponse descriptor];
  GPBOneofDescriptor *oneof = [descriptor.oneofs objectAtIndex:0];
  GPBClearOneof(message, oneof);
}
#pragma mark - BlockHeaders

@implementation BlockHeaders

@dynamic headersArray, headersArray_Count;

typedef struct BlockHeaders__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *headersArray;
} BlockHeaders__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "headersArray",
        .dataTypeSpecific.clazz = Nil,
        .number = BlockHeaders_FieldNumber_HeadersArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(BlockHeaders__storage_, headersArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BlockHeaders class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BlockHeaders__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetEstimatedTransactionFeeRequest

@implementation GetEstimatedTransactionFeeRequest

@dynamic blocks;

typedef struct GetEstimatedTransactionFeeRequest__storage_ {
  uint32_t _has_storage_[1];
  uint32_t blocks;
} GetEstimatedTransactionFeeRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "blocks",
        .dataTypeSpecific.clazz = Nil,
        .number = GetEstimatedTransactionFeeRequest_FieldNumber_Blocks,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetEstimatedTransactionFeeRequest__storage_, blocks),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetEstimatedTransactionFeeRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetEstimatedTransactionFeeRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetEstimatedTransactionFeeResponse

@implementation GetEstimatedTransactionFeeResponse

@dynamic fee;

typedef struct GetEstimatedTransactionFeeResponse__storage_ {
  uint32_t _has_storage_[1];
  double fee;
} GetEstimatedTransactionFeeResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fee",
        .dataTypeSpecific.clazz = Nil,
        .number = GetEstimatedTransactionFeeResponse_FieldNumber_Fee,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetEstimatedTransactionFeeResponse__storage_, fee),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetEstimatedTransactionFeeResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetEstimatedTransactionFeeResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - TransactionsWithProofsRequest

@implementation TransactionsWithProofsRequest

@dynamic fromBlockOneOfCase;
@dynamic hasBloomFilter, bloomFilter;
@dynamic fromBlockHash;
@dynamic fromBlockHeight;
@dynamic count;
@dynamic sendTransactionHashes;

typedef struct TransactionsWithProofsRequest__storage_ {
  uint32_t _has_storage_[2];
  uint32_t fromBlockHeight;
  uint32_t count;
  BloomFilter *bloomFilter;
  NSData *fromBlockHash;
} TransactionsWithProofsRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "bloomFilter",
        .dataTypeSpecific.clazz = GPBObjCClass(BloomFilter),
        .number = TransactionsWithProofsRequest_FieldNumber_BloomFilter,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TransactionsWithProofsRequest__storage_, bloomFilter),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "fromBlockHash",
        .dataTypeSpecific.clazz = Nil,
        .number = TransactionsWithProofsRequest_FieldNumber_FromBlockHash,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(TransactionsWithProofsRequest__storage_, fromBlockHash),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "fromBlockHeight",
        .dataTypeSpecific.clazz = Nil,
        .number = TransactionsWithProofsRequest_FieldNumber_FromBlockHeight,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(TransactionsWithProofsRequest__storage_, fromBlockHeight),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "count",
        .dataTypeSpecific.clazz = Nil,
        .number = TransactionsWithProofsRequest_FieldNumber_Count,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(TransactionsWithProofsRequest__storage_, count),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "sendTransactionHashes",
        .dataTypeSpecific.clazz = Nil,
        .number = TransactionsWithProofsRequest_FieldNumber_SendTransactionHashes,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TransactionsWithProofsRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TransactionsWithProofsRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    static const char *oneofs[] = {
      "fromBlock",
    };
    [localDescriptor setupOneofs:oneofs
                           count:(uint32_t)(sizeof(oneofs) / sizeof(char*))
                   firstHasIndex:-1];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void TransactionsWithProofsRequest_ClearFromBlockOneOfCase(TransactionsWithProofsRequest *message) {
  GPBDescriptor *descriptor = [TransactionsWithProofsRequest descriptor];
  GPBOneofDescriptor *oneof = [descriptor.oneofs objectAtIndex:0];
  GPBClearOneof(message, oneof);
}
#pragma mark - BloomFilter

@implementation BloomFilter

@dynamic vData;
@dynamic nHashFuncs;
@dynamic nTweak;
@dynamic nFlags;

typedef struct BloomFilter__storage_ {
  uint32_t _has_storage_[1];
  uint32_t nHashFuncs;
  uint32_t nTweak;
  uint32_t nFlags;
  NSData *vData;
} BloomFilter__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "vData",
        .dataTypeSpecific.clazz = Nil,
        .number = BloomFilter_FieldNumber_VData,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BloomFilter__storage_, vData),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "nHashFuncs",
        .dataTypeSpecific.clazz = Nil,
        .number = BloomFilter_FieldNumber_NHashFuncs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BloomFilter__storage_, nHashFuncs),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "nTweak",
        .dataTypeSpecific.clazz = Nil,
        .number = BloomFilter_FieldNumber_NTweak,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BloomFilter__storage_, nTweak),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "nFlags",
        .dataTypeSpecific.clazz = Nil,
        .number = BloomFilter_FieldNumber_NFlags,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BloomFilter__storage_, nFlags),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BloomFilter class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BloomFilter__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - TransactionsWithProofsResponse

@implementation TransactionsWithProofsResponse

@dynamic responsesOneOfCase;
@dynamic rawTransactions;
@dynamic instantSendLockMessages;
@dynamic rawMerkleBlock;

typedef struct TransactionsWithProofsResponse__storage_ {
  uint32_t _has_storage_[2];
  RawTransactions *rawTransactions;
  InstantSendLockMessages *instantSendLockMessages;
  NSData *rawMerkleBlock;
} TransactionsWithProofsResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "rawTransactions",
        .dataTypeSpecific.clazz = GPBObjCClass(RawTransactions),
        .number = TransactionsWithProofsResponse_FieldNumber_RawTransactions,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(TransactionsWithProofsResponse__storage_, rawTransactions),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "instantSendLockMessages",
        .dataTypeSpecific.clazz = GPBObjCClass(InstantSendLockMessages),
        .number = TransactionsWithProofsResponse_FieldNumber_InstantSendLockMessages,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(TransactionsWithProofsResponse__storage_, instantSendLockMessages),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "rawMerkleBlock",
        .dataTypeSpecific.clazz = Nil,
        .number = TransactionsWithProofsResponse_FieldNumber_RawMerkleBlock,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(TransactionsWithProofsResponse__storage_, rawMerkleBlock),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TransactionsWithProofsResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TransactionsWithProofsResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    static const char *oneofs[] = {
      "responses",
    };
    [localDescriptor setupOneofs:oneofs
                           count:(uint32_t)(sizeof(oneofs) / sizeof(char*))
                   firstHasIndex:-1];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

void TransactionsWithProofsResponse_ClearResponsesOneOfCase(TransactionsWithProofsResponse *message) {
  GPBDescriptor *descriptor = [TransactionsWithProofsResponse descriptor];
  GPBOneofDescriptor *oneof = [descriptor.oneofs objectAtIndex:0];
  GPBClearOneof(message, oneof);
}
#pragma mark - RawTransactions

@implementation RawTransactions

@dynamic transactionsArray, transactionsArray_Count;

typedef struct RawTransactions__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *transactionsArray;
} RawTransactions__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "transactionsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = RawTransactions_FieldNumber_TransactionsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RawTransactions__storage_, transactionsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RawTransactions class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RawTransactions__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - InstantSendLockMessages

@implementation InstantSendLockMessages

@dynamic messagesArray, messagesArray_Count;

typedef struct InstantSendLockMessages__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *messagesArray;
} InstantSendLockMessages__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messagesArray",
        .dataTypeSpecific.clazz = Nil,
        .number = InstantSendLockMessages_FieldNumber_MessagesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(InstantSendLockMessages__storage_, messagesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[InstantSendLockMessages class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(InstantSendLockMessages__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MasternodeListRequest

@implementation MasternodeListRequest


typedef struct MasternodeListRequest__storage_ {
  uint32_t _has_storage_[1];
} MasternodeListRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MasternodeListRequest class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(MasternodeListRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MasternodeListResponse

@implementation MasternodeListResponse

@dynamic masternodeListDiff;

typedef struct MasternodeListResponse__storage_ {
  uint32_t _has_storage_[1];
  NSData *masternodeListDiff;
} MasternodeListResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "masternodeListDiff",
        .dataTypeSpecific.clazz = Nil,
        .number = MasternodeListResponse_FieldNumber_MasternodeListDiff,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MasternodeListResponse__storage_, masternodeListDiff),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MasternodeListResponse class]
                                     rootClass:[CoreRoot class]
                                          file:CoreRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MasternodeListResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
