export const PREFETCHED = 'prefetched';
export const CREATED = 'created';
export const STARTED = 'started';
export const READY = 'ready';
export const CONFIRMED_BALANCE_CHANGED = 'confirmed_balance_changed';
export const UNCONFIRMED_BALANCE_CHANGED = 'unconfirmed_balance_changed';
export const BLOCKHEIGHT_CHANGED = 'blockheight_changed';
export const BLOCK = 'block';
export const TRANSACTION = 'transaction';
export const BLOCKHEADER = 'blockheader';
export const FETCHED_ADDRESS = 'FETCHED/ADDRESS';
export const ERROR_UPDATE_ADDRESS = 'ERROR/UPDATE_ADDRESS';
export const FETCHED_TRANSACTION = 'FETCHED/TRANSACTION';
export const FETCHED_UNCONFIRMED_TRANSACTION = 'FETCHED/UNCONFIRMED_TRANSACTION';
export const FETCHED_CONFIRMED_TRANSACTION = 'FETCHED/CONFIRMED_TRANSACTION';
export const CONFIRMED_TRANSACTION = 'CONFIRMED_TRANSACTION';
export const GENERATED_ADDRESS = 'GENERATED_ADDRESS';
export const DISCOVERY_STARTED = 'DISCOVERY_STARTED';
export const CONFIGURED = 'CONFIGURED';
export const INITIALIZED = 'INITIALIZED';
export const SAVE_STATE_FAILED = 'SAVE_STATE_FAILED';
export const SAVE_STATE_SUCCESS = 'SAVE_STATE_SUCCESS';
export const REHYDRATE_STATE_FAILED = 'REHYDRATE_STATE_FAILED';
export const REHYDRATE_STATE_SUCCESS = 'REHYDRATE_STATE_SUCCESS';
export const INSTANT_LOCK = 'INSTANT_LOCK';
export const TX_METADATA = 'TX_METADATA';
export const HEADERS_SYNC_PROGRESS = 'HEADERS_SYNC_PROGRESS';
export const TRANSACTIONS_SYNC_PROGRESS = 'TRANSACTIONS_SYNC_PROGRESS';

export default {
  PREFETCHED,
  CREATED,
  STARTED,
  READY,
  CONFIRMED_BALANCE_CHANGED,
  UNCONFIRMED_BALANCE_CHANGED,
  BLOCKHEIGHT_CHANGED,
  BLOCK,
  TRANSACTION,
  BLOCKHEADER,
  FETCHED_ADDRESS,
  ERROR_UPDATE_ADDRESS,
  FETCHED_TRANSACTION,
  FETCHED_UNCONFIRMED_TRANSACTION,
  FETCHED_CONFIRMED_TRANSACTION,
  CONFIRMED_TRANSACTION,
  GENERATED_ADDRESS,
  DISCOVERY_STARTED,
  CONFIGURED,
  INITIALIZED,
  SAVE_STATE_FAILED,
  SAVE_STATE_SUCCESS,
  REHYDRATE_STATE_FAILED,
  REHYDRATE_STATE_SUCCESS,
  INSTANT_LOCK,
  TX_METADATA,
  HEADERS_SYNC_PROGRESS,
  TRANSACTIONS_SYNC_PROGRESS,
};
