# REMOVE THIS FILE after merging fix/clippy-tests-etc
name: Tests rs-drive-abci

on:
  workflow_dispatch:
  push:
    branches:
      - fix/clippy-tests-etc


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drive-abci-tests:
    name: Drive ABCI tests
    secrets: inherit
    uses: ./.github/workflows/tests-rs-package.yml
    with:
      package: drive-abci
      check-each-feature: true
      direct-packages: '["drive-abci"]'
