name: Security Audits

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rs-crates-security:
    name: Rust crates security audit
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup sccache
        uses: ./.github/actions/sccache
        with:
          bucket: ${{ vars.CACHE_S3_BUCKET }}
          region: ${{ vars.CACHE_REGION }}
          endpoint: ${{ vars.CACHE_S3_ENDPOINT }}
          access_key_id: ${{ secrets.CACHE_KEY_ID }}
          secret_access_key: ${{ secrets.CACHE_SECRET_KEY }}

      - name: Audit crates
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  js-npm-security:
    name: JS NPM security audit
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Audit NPM
        run: yarn npm audit --environment production --all --recursive

  build-js:
    name: Build JS packages
    secrets: inherit
    uses: ./.github/workflows/tests-build-js.yml

  js-codeql:
    name: JS code security audit
    needs: build-js
    secrets: inherit
    uses: ./.github/workflows/tests-codeql.yml
