on:
  workflow_call:
    inputs:
      image_org:
        type: string
        description: Registry and namespace for CI images
        required: false
        default: ghcr.io/dashpay/platform-ci
      image_tag:
        type: string
        description: Tag for pre-built images
        required: true

jobs:
  test-functional:
    name: Run functional tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start local network
        uses: ./.github/actions/local-network
        with:
          image_org: ${{ inputs.image_org }}
          image_tag: ${{ inputs.image_tag }}

      - name: Run Wallet functional tests
        run: yarn workspace @dashevo/wallet-lib test:functional

      - name: Run SDK functional tests
        run: yarn workspace dash test:functional

      - name: Run WASM SDK functional tests
        run: yarn workspace @dashevo/wasm-sdk test:functional

      - name: Show Docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2
