on:
  workflow_call:
    inputs:
      name:
        type: string
        description: Name
        required: true
      test-pattern:
        type: string
        description: Test pattern. i.e. test/e2e/*.spec.js
        required: true
      restore_local_network_data:
        type: boolean
        description: Load local network data from cache
        default: false
      image_org:
        type: string
        description: Registry and namespace for CI images
        required: false
        default: ghcr.io/dashpay/platform-ci
      image_tag:
        type: string
        description: Tag for pre-built images
        required: true

jobs:
  dashmate-test:
    name: Run ${{ inputs.name }} tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.JS
        uses: ./.github/actions/nodejs

      - name: Download JS build artifacts
        uses: actions/download-artifact@v4
        with:
          name: js-build-${{ github.sha }}
          path: packages

      - name: Replace with pre-built images
        run: |
          set -e

          IMAGE_ORG="${{ inputs.image_org }}"
          IMAGE_TAG="${{ inputs.image_tag }}"

          # Drive
          DRIVE_IMAGE_AND_VERSION=$(yarn dashmate config get --config=local platform.drive.abci.docker.image)
          docker pull $IMAGE_ORG/drive:$IMAGE_TAG
          docker tag $IMAGE_ORG/drive:$IMAGE_TAG $DRIVE_IMAGE_AND_VERSION

          # RS-DAPI
          RS_DAPI_IMAGE_AND_VERSION=$(yarn dashmate config get --config=local platform.dapi.rsDapi.docker.image)
          docker pull $IMAGE_ORG/rs-dapi:$IMAGE_TAG
          docker tag $IMAGE_ORG/rs-dapi:$IMAGE_TAG $RS_DAPI_IMAGE_AND_VERSION

          # Dashmate helper image is hardcoded so we replace it with the built one
          VERSION=$(cat package.json | jq -r '.version')
          docker pull $IMAGE_ORG/dashmate-helper:$IMAGE_TAG
          docker tag $IMAGE_ORG/dashmate-helper:$IMAGE_TAG dashpay/dashmate-helper:${VERSION}
        shell: bash

      - name: Get dashmate fingerprint
        id: dashmate-fingerprint
        run: echo "sha=$(git log -1 --format="%h" -- packages/dashmate)" >> $GITHUB_OUTPUT
        if: inputs.restore_local_network_data == true

      - name: Set HOME variable to github context
        shell: bash
        run: echo "HOME=$HOME" >> $GITHUB_ENV

      - name: Restore test suite local network data to speed up dashmate local network tests
        id: local-network-data
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.HOME }}/.dashmate
            **/.env
            dashmate_volumes_dump
          key: local-network-volumes/${{ steps.dashmate-fingerprint.outputs.sha }}
        if: inputs.restore_local_network_data == true

      - name: Restore dashmate volumes
        run: ./scripts/dashmate/volumes/restore.sh
        if: steps.local-network-data.outputs.cache-hit == 'true'

      - name: Run tests with cache
        run: yarn workspace dashmate run mocha ${{ inputs.test-pattern }}
        env:
          DEBUG: 1
          DASHMATE_E2E_TESTS_SKIP_IMAGE_BUILD: true
          DASHMATE_E2E_TESTS_LOCAL_HOMEDIR: ${{ env.HOME }}/.dashmate
        if: steps.local-network-data.outputs.cache-hit == 'true'

      - name: Run tests without cache
        run: yarn workspace dashmate run mocha ${{ inputs.test-pattern }}
        env:
          DEBUG: 1
          DASHMATE_E2E_TESTS_SKIP_IMAGE_BUILD: true
        if: steps.local-network-data.outputs.cache-hit == 'false'

      - name: Show Docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2
