on:
  workflow_call:
    inputs:
      name:
        type: string
        description: Name
        required: true
      command:
        description: Run tests command
        type: string
        default: test
        required: true
      batch_index:
        description: Browser test batch index
        type: number
        default: 0
      batch_total:
        description: Browser test batch total
        type: number
        default: 0
      image_org:
        type: string
        description: Registry and namespace for CI images
        required: false
        default: ghcr.io/dashpay/platform-ci
      image_tag:
        type: string
        description: Tag for pre-built images
        required: true

jobs:
  test-suite:
    name: Run ${{ inputs.name }}
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start local network
        uses: ./.github/actions/local-network
        with:
          image_org: ${{ inputs.image_org }}
          image_tag: ${{ inputs.image_tag }}

      - name: Run test suite
        run: yarn workspace @dashevo/platform-test-suite ${{ inputs.command }}
        env:
          BROWSER_TEST_BATCH_INDEX: ${{ inputs.batch_index }}
          BROWSER_TEST_BATCH_TOTAL: ${{ inputs.batch_total }}

      - name: Show Docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2
